export const diagnosis = [
  { category: 'Lung Cancer', name: 'Lung cancer, main bronchus, carina (162.2, C34.00)' },
  { category: 'Lung Cancer', name: 'Lung cancer, upper lobe (162.3, C34.10)' },
  { category: 'Lung Cancer', name: 'Lung cancer, middle lobe (162.4, C34.2)' },
  { category: 'Lung Cancer', name: 'Lung cancer, lower lobe (162.5, C34.30)' },
  {
    category: 'Lung Cancer',
    name: 'Malignant neoplasm other parts of bronchus or lung (162.8, C34.8)',
  },
  { category: 'Lung Cancer', name: 'Lung cancer, location unspecified (162.9, C34.90)' },
  { category: 'Lung Cancer', name: 'Lung tumor, metastatic (197.0, C78.00)' },
  {
    category: 'Lung Cancer',
    name: 'Personal history of malignant neoplasm of bronchus and lung (V10.11, Z85.118)',
  },
  {
    category: 'Lung Cancer',
    name: 'Neoplasm of uncertain behavior of trachea, bronchus and lung (235.7, DM38.1)',
  },
  { category: 'Esophageal cancer', name: 'Esophageal cancer, upper third (150.3, C15.3)' },
  { category: 'Esophageal cancer', name: 'Esophageal cancer, middle third (150.4, C15.4)' },
  { category: 'Esophageal cancer', name: 'Esophageal cancer, lower third (150.5, C15.5)' },
  {
    category: 'Esophageal cancer',
    name: 'Esophageal cancer, esophagogastric junction (cardia) (151.0, C16.0)',
  },
  { category: 'Esophageal cancer', name: 'Malignant neo stomach unspecified (151.9, C16.9)' },
  {
    category: 'Esophageal cancer',
    name: 'Malignant other part esophagus, specified (150.8, C15.8)',
  },
  {
    category: 'Esophageal cancer',
    name: 'Malignant neoplasm of the esophagus, unspecified (150.9, C15.9)',
  },
  { category: 'Thymus/Mediastinal Mass', name: 'Myasthenia gravis (358.0, G70.00)' },
  {
    category: 'Thymus/Mediastinal Mass',
    name: 'Anterior mediastinal tumor - primary(germ cell cancer, seminoma) (164.2, C38.1)',
  },
  {
    category: 'Thymus/Mediastinal Mass',
    name: 'Anterior mediastinal tumor - metastatic (197.1, C78.1)',
  },
  {
    category: 'Thymus/Mediastinal Mass',
    name: 'Anterior mediastinal tumor - benign (e.g., teratoma) (212.5, D15.2)',
  },
  {
    category: 'Thymus/Mediastinal Mass',
    name: 'Anterior mediastinal tumor - thymus tumor (thymoma, thymic carcinoma) (164.0, C37)',
  },
  {
    category: 'Thymus/Mediastinal Mass',
    name: 'Posterior mediastinal tumor - primary (164.3, C38.2)',
  },
  {
    category: 'Thymus/Mediastinal Mass',
    name: 'Posterior mediastinal tumor - metastatic (197.1, C78.1)',
  },
  {
    category: 'Thymus/Mediastinal Mass',
    name: 'Neoplasm of uncertain behavior of pleura, thymus, mediastinum (235.8, D38.2-D38.4)',
  },
  { category: 'Trachea', name: 'Tracheal tumor, benign (212.2, D14.2)' },
  { category: 'Trachea', name: 'Tracheal tumor, malignant (162.0, C33)' },
  { category: 'Trachea', name: 'Tracheal tumor, metastatic (197.3, C78.30)' },
  { category: 'Trachea', name: 'Tracheal stenosis, acquired (519.19, J39.8)' },
  { category: 'Trachea', name: 'Tracheal stenosis, congenital (748.3, Q32.1)' },
  { category: 'Trachea', name: 'Subglottic stenosis - acquired (post intubation) (478.74, J38.6)' },
  { category: 'Trachea', name: 'Subglottic stenosis - congenital (748.3, Q31.1)' },
  { category: 'Trachea', name: 'Tracheostomy related stenosis (519.02, J95.03)' },
  { category: 'Hiatal Hernia/GERD', name: 'Esophageal reflux (GERD) (530.81, K21.9)' },
  { category: 'Hiatal Hernia/GERD', name: 'Reflux esophagitis (530.11, K21.0)' },
  { category: 'Hiatal Hernia/GERD', name: 'Barrett’s esophagus (530.85, K22.70)' },
  {
    category: 'Hiatal Hernia/GERD',
    name: 'Barrett’s esophagus with High Grade Dysplasia (530.85, K22.711)',
  },
  {
    category: 'Hiatal Hernia/GERD',
    name: 'Diaphragmatic hernia without obstruction or gangrene (553.3, K44.9)',
  },
  {
    category: 'Hiatal Hernia/GERD',
    name: 'Diaphragmatic hernia with obstruction, without gangrene (552.3, K44.0)',
  },
  { category: 'Hiatal Hernia/GERD', name: 'Diaphragmatic hernia with gangrene (551.3, K44.1)' },
  { category: 'Cardiovascular', name: 'Cardiac tamponade (423.3, I31.4)' },
  { category: 'Cardiovascular', name: 'Pericarditis with effusion (420.9, I30.9)' },
  { category: 'Cardiovascular', name: 'Pericarditis, constrictive (432.2, I31.1)' },
  { category: 'Cardiovascular', name: 'Pericardial effusion, malignant (198.89, C79.89)' },
  { category: 'Cardiovascular', name: 'SVC Syndrome (459.2, I87.1)' },
  { category: 'Cardiovascular', name: 'Unspecified disease of the pericardium (423.9, I31.9)' },
  { category: 'Chest Wall', name: 'Pectus carinatum (754.82, Q67.7)' },
  { category: 'Chest Wall', name: 'Pectus excavatum (754.81, Q67.6)' },
  { category: 'Chest Wall', name: 'Rib tumor, benign (e.g., fibrous dysplasia) (213.3, D16.7)' },
  {
    category: 'Chest Wall',
    name: 'Rib tumor, malignant (e.g., osteosarcoma, chondrosarcoma) (170.3, C41.3)',
  },
  { category: 'Chest Wall', name: 'Rib tumor, metastatic (198.5, C79.51)' },
  { category: 'Chest Wall', name: 'Sternal tumor, benign (213.3, D16.7)' },
  { category: 'Chest Wall', name: 'Sternal tumor, malignant (170.3, C41.3)' },
  { category: 'Chest Wall', name: 'Sternal tumor, metastatic (198.5, C79.51)' },
  { category: 'Chest Wall', name: 'Thoracic outlet syndrome (353.0, G54.0)' },
  { category: 'Diaphragm', name: 'Diaphragm tumor, benign (215.4, D21.3)' },
  { category: 'Diaphragm', name: 'Diaphragm tumor, malignant (171.4, C49.3)' },
  { category: 'Diaphragm', name: 'Diaphragm tumor, metastatic (198.89, C79.89)' },
  { category: 'Diaphragm', name: 'Diaphragmatic paralysis (519.4, J98.6)' },
  { category: 'Esophagus - Other', name: 'Foreign body esophagus (935.1, T18.108a)' },
  {
    category: 'Esophagus - Other',
    name: 'Acquired absence of esophagus (post esophagectomy) (V45.79, Z90.89)',
  },
  { category: 'Esophagus - Other', name: 'Achalasia of esophagus (530.0, K22.0)' },
  { category: 'Esophagus - Other', name: 'Dyskinesia/spasm of esophagus (530.5, K22.4)' },
  { category: 'Esophagus - Other', name: 'Esophageal stricture (530.3, K22.2)' },
  {
    category: 'Esophagus - Other',
    name: 'Esophageal tumor-benign (i.e., leiomyoma) (211.0, D13.0)',
  },
  {
    category: 'Esophagus - Other',
    name: 'Gastric outlet obstruction, pyloric stenosis, acquired (537.0, K31.1)',
  },
  { category: 'Esophagus - Other', name: 'Esophageal perforation (530.4, K22.3)' },
  { category: 'Esophagus - Other', name: 'Mallory Weiss tear (530.7, K22.6)' },
  { category: 'Esophagus - Other', name: 'Tracheoesophageal fistula (530.84, J86.0)' },
  { category: 'Esophagus - Other', name: 'Esophagitis (530.1, K20.9)' },
  { category: 'Esophagus - Other', name: 'Zenkers diverticulum (530.6, K22.5)' },
  { category: 'Esophagus - Other', name: 'Epiphrenic diverticulum (530.6, K22.5)' },
  { category: 'Esophagus - Other', name: 'Ulcer esophagus with bleeding (530.21, K22.11)' },
  { category: 'Esophagus - Other', name: 'Ulcer esophagus without bleeding (530.2, K22.10)' },
  { category: 'Esophagus - Other', name: 'Other disease of the esophagus (530.89, K22.8)' },
  { category: 'Esophagus - Other', name: 'Other digestive system complication (997.49, K91.XX)' },
  { category: 'Lung – Other', name: 'Acute respiratory failure (518.81, J96.00)' },
  { category: 'Lung – Other', name: 'Pneumonia (486.0, J18.9)' },
  {
    category: 'Lung – Other',
    name: 'Pulmonary insufficiency following surgery/trauma (ARDS) (518.5, J95.82)',
  },
  { category: 'Lung – Other', name: 'Aspergillosis (117.3, B44.9)' },
  { category: 'Lung – Other', name: 'Bronchiectasis (494.0, J47.9)' },
  {
    category: 'Lung – Other',
    name: 'Cystic fibrosis with pulmonary manifestations (277.02, E84.0)',
  },
  { category: 'Lung – Other', name: 'Emphysema (492.8, J43.8)' },
  { category: 'Lung – Other', name: 'Emphysematous bleb (492.0, J43.9)' },
  { category: 'Lung – Other', name: 'Lung abscess (513.0, J85.2)' },
  { category: 'Lung – Other', name: 'Interstitial lung disease/fibrosis (516.3, J84.1)' },
  { category: 'Lung – Other', name: 'Post inflammatory pulmonary fibrosis (515, J84.89)' },
  { category: 'Lung – Other', name: 'Hemothorax (511.8, J94.2)' },
  { category: 'Lung – Other', name: 'Pneumothorax (512.8, J93.1)' },
  {
    category: 'Lung – Other',
    name: 'Solitary pulmonary nodule (not a tumor, e.g., granuloma, subpleural lymph node, pulmonary infarct) (793.11, R91.1)',
  },
  { category: 'Lung – Other', name: 'Lung tumor, benign (e.g., hamartoma) (212.3, D14.30)' },
  { category: 'Lung – Other', name: 'Pulmonary sequestration (748.5, Q33.2)' },
  { category: 'Lung – Other', name: 'Primary pulmonary hypertension (416.0, I 27.0)' },
  { category: 'Lung – Other', name: 'Transplanted lung complication(s) (996.84, T86.8XX)' },
  { category: 'Lung – Other', name: 'Gangrene and necrosis of lung (513.0, J85.0)' },
  { category: 'Mediastinum', name: 'Mediastinal nodes, metastatic (196.1, C77.1)' },
  { category: 'Mediastinum', name: 'Benign neoplasm of thymus (212.6, D15.0)' },
  { category: 'Mediastinum', name: 'Lymphoma, intrathoracic (202.82, C85.92)' },
  { category: 'Mediastinum', name: 'Mediastinal abscess (513.1, J85.3)' },
  { category: 'Mediastinum', name: 'Mediastinal cyst, Bronchogenic (519.3, J98.5)' },
  { category: 'Mediastinum', name: 'Mediastinal cyst, Foregut duplication (519.3, J98.5)' },
  { category: 'Mediastinum', name: 'Mediastinal cyst, Pericardial (519.3, J98.5)' },
  { category: 'Mediastinum', name: 'Mediastinal cyst, Thymic (519.3, J98.5)' },
  { category: 'Mediastinum', name: 'Mediastinal nodes, benign (229.0, D36.0)' },
  { category: 'Mediastinum', name: 'Mediastinitis (519.2, J98.5)' },
  {
    category: 'Mediastinum',
    name: 'Posterior mediastinal tumor-benign (neurogenic) (212.5, D15.2)',
  },
  { category: 'Mediastinum', name: 'Unspecified disease of thymus gland (254.9, E32.9)' },
  { category: 'Pleura', name: 'Pleural effusion, infected - (empyema) (511.1, J86.9)' },
  { category: 'Pleura', name: 'Pleural effusion, malignant (197.2, C78.2)' },
  { category: 'Pleura', name: 'Pleural effusion, sterile (511.9, J90)' },
  { category: 'Pleura', name: 'Pleural effusion, other specified, except TB (511.89, J90)' },
  { category: 'Pleura', name: 'Pleural effusion, TB; (Tuberculous pleurisy) (012.0, A15.6)' },
  { category: 'Pleura', name: 'Pleural thickening (511.0, J94.9)' },
  { category: 'Pleura', name: 'Empyema with fistula (510.0, J86.0)' },
  { category: 'Pleura', name: 'Empyema without fistula (510.9, J86.9)' },
  { category: 'Pleura', name: 'Empyema, tuberculosis (A15.6)' },
  { category: 'Pleura', name: 'Pleural tumor, benign (212.4, D19.0)' },
  { category: 'Pleura', name: 'Pleural tumor, metastatic (197.2, C78.2)' },
  { category: 'Pleura', name: 'Malignant neoplasm other specified sites of pleura (163.8, C38.4)' },
  {
    category: 'Pleura',
    name: 'Malignant tumor of pleura, unspecified (e.g., mesothelioma) (163.9, C45)',
  },
  { category: 'Thyroid', name: 'Goiter, nodular (241.9, E04.9)' },
  { category: 'Thyroid', name: 'Thyroid neoplasm, benign (226.0, D34)' },
  { category: 'Thyroid', name: 'Thyroid neoplasm, malignant (193.0, C73)' },
  { category: 'Trachea & Larynx', name: 'Dysphagia, unspecified (787.2, R13.10)' },
  { category: 'Trachea & Larynx', name: 'Tracheomalacia - congenital (748.3, Q32.0)' },
  { category: 'Trachea & Larynx', name: 'Tracheomalacia - acquired (519.1, J39.8)' },
  { category: 'Trachea & Larynx', name: 'Tracheostomy - hemorrhage (519.09, J95.01)' },
  { category: 'Trachea & Larynx', name: 'Vocal cord paralysis, unilateral (478.31, J38.01)' },
  { category: 'Trachea & Larynx', name: 'Vocal cord paralysis, bilateral (478.33, J38.02)' },
  { category: 'Trachea & Larynx', name: 'Vocal cord paralysis, unspecified (478.3, J38.00)' },
  { category: 'Trauma', name: 'Flail chest (807.4, S22.5xxa)' },
  { category: 'Trauma', name: 'Rib fracture (807.0, S22.39xa)' },
  { category: 'Trauma', name: 'Rib fractures, multiple (807.0, S22.49xa)' },
  { category: 'Trauma', name: 'Sternal fracture (807.2, S22.20xa)' },
  { category: 'Trauma', name: 'Tracheal injury (807.5, S12.8xxa)' },
  { category: 'Trauma', name: 'Traumatic pneumothorax (860.0, S27.0xxa)' },
  { category: 'Miscellaneous', name: 'Abnormal radiologic finding (793.1, R91)' },
  {
    category: 'Miscellaneous',
    name: 'Chronic airway obstruction not elsewhere classified (496, J44.9)',
  },
  { category: 'Miscellaneous', name: 'Chylothorax (457.8, 189.8)' },
  {
    category: 'Miscellaneous',
    name: 'Disruption of internal operation, surgical wound (998.31, T81.32XA)',
  },
  {
    category: 'Miscellaneous',
    name: 'Hemorrhage complicating a procedure (998.11, multiple codes)',
  },
  { category: 'Miscellaneous', name: 'Hematoma complicating a procedure (998.12, multiple codes)' },
  { category: 'Miscellaneous', name: 'Hemoptysis unspecified (786.3, R04.2)' },
  { category: 'Miscellaneous', name: 'Hyperhidrosis, focal; axilla (705.21, L74.510)' },
  { category: 'Miscellaneous', name: 'Hyperhidrosis, focal; face (705.21, L74.511)' },
  { category: 'Miscellaneous', name: 'Hyperhidrosis, focal; palms (705.21, L74.512)' },
  { category: 'Miscellaneous', name: 'Lymphadenopathy (785.6, R59.9)' },
  {
    category: 'Miscellaneous',
    name: 'Other non-infectious disorders of lymphatic channels (457.8, I89.8)',
  },
  {
    category: 'Miscellaneous',
    name: 'Malignant neoplasm of connective tissue and other soft tissue of the thorax (171.4, C49.3)',
  },
  {
    category: 'Miscellaneous',
    name: 'Malignant poorly differentiated neuroendocrine carcinoma, any site (209.3, C74.1)',
  },
  { category: 'Miscellaneous', name: 'Non-healing surgical wound (998.83, T81.89XA)' },
  { category: 'Miscellaneous', name: 'Other post- op infection (998.59, T81.4XXA)' },
  {
    category: 'Miscellaneous',
    name: 'Persistent post-op fistula not otherwise classified (998.6, T81.83XA)',
  },
  { category: 'Miscellaneous', name: 'Post-operative air leak (512.2, J95.812)' },
  {
    category: 'Miscellaneous',
    name: 'Secondary malignant neoplasm of other specified sites (198.89, C79.89)',
  },
  { category: 'Miscellaneous', name: 'Shortness of breath (786.05, R06.02)' },
  { category: 'Miscellaneous', name: 'Swelling, mass or lump in chest (786.6, R22.2)' },
  { category: 'Miscellaneous', name: 'Other unlisted category of disease' },
];

export const procedure = [
  { category: 'Lung Cancer Resection', name: 'Thoracoscopy with lobectomy (32663)' },
  {
    category: 'Lung Cancer Resection',
    name: 'Thoracoscopy with therapeutic wedge resection (eg mass or nodule, initial, unilateral (32666)',
  },
  {
    category: 'Lung Cancer Resection',
    name: 'Thoracoscopy with therapeutic wedge resection (eg mass or nodule) each additional resection, ipsilateral (+32667)',
  },
  {
    category: 'Lung Cancer Resection',
    name: 'Thoracoscopy with diagnostic wedge resection followed by anatomiclungresection (+32668)',
  },
  {
    category: 'Lung Cancer Resection',
    name: 'Thoracoscopy with removal of a single lung segment (segmentectomy) (32669)',
  },
  {
    category: 'Lung Cancer Resection',
    name: 'Thoracoscopy with removal of two lobes (bilobectomy) (32670)',
  },
  {
    category: 'Lung Cancer Resection',
    name: 'Thoracoscopy with removal of lung, pneumonectomy (32671)',
  },
  {
    category: 'Lung Cancer Resection',
    name: 'Thoracoscopy with mediastinal and regional lymphadenectomy (+32674)',
  },
  {
    category: 'Lung Cancer Resection',
    name: 'Thoracotomy with therapeutic wedge resection (eg mass nodule) initial (32505)',
  },
  {
    category: 'Lung Cancer Resection',
    name: 'Removal of lung, single segment (segmentectomy) (32484)',
  },
  { category: 'Lung Cancer Resection', name: 'Removal of lung, single lobe (lobectomy) (32480)' },
  { category: 'Lung Cancer Resection', name: 'Removal of lung, two lobes (bilobectomy) (32482)' },
  { category: 'Lung Cancer Resection', name: 'Removal of lung, sleeve lobectomy (32486)' },
  { category: 'Lung Cancer Resection', name: 'Removal of lung, total pneumonectomy (32440)' },
  {
    category: 'Lung Cancer Resection',
    name: 'Removal of lung, sleeve (carinal) pneumonectomy (32442)',
  },
  { category: 'Lung Cancer Resection', name: 'Removal of lung, completion pneumonectomy (32488)' },
  {
    category: 'Lung Cancer Resection',
    name: 'Resection and repair of portion of bronchus (bronchoplasty) when performed at time of lobectomy or segmentectomy (32501)',
  },
  {
    category: 'Lung Cancer Resection',
    name:
      'Resection of apical lung tumor (e.g., Pancoast tumor), including chest wall resection, without chest wall reconstruction(s) (32503)',
  },
  {
    category: 'Lung Cancer Resection',
    name: 'Resection of apical lung tumor (e.g., Pancoast tumor), including chest wall resection, with chest wall reconstruction (32504)',
  },
  {
    category: 'Lung Cancer Resection',
    name: 'Thoracotomy with therapeutic wedge resection (e.g., mass nodule) each additional resection, ipsilateral (+32506)',
  },
  {
    category: 'Lung Cancer Resection',
    name: 'Thoracotomy with diagnostic wedge resection followed by anatomic lung resection (+32507)',
  },
  {
    category: 'Lung Cancer Resection',
    name: 'Thoracic lymphadenectomy, regional, including mediastinal and peritracheal nodes (38746)',
  },
  {
    category: 'Esophagus Resection',
    name: 'Transhiatal - Total esophagectomy, without thoracotomy, with cervical esophagogastrostomy (43107)',
  },
  {
    category: 'Esophagus Resection',
    name: 'Total esophagectomy, without thoracotomy, with colon interposition or small intestine reconstruction (43108)',
  },
  {
    category: 'Esophagus Resection',
    name: 'Three Incision - Total esophagectomy with thoracotomy, with cervical esophagogastrostomy (43112)',
  },
  {
    category: 'Esophagus Resection',
    name: 'Total esophagectomy with thoracotomy, with colon interposition or small intestine reconstruction (43113)',
  },
  {
    category: 'Esophagus Resection',
    name: 'Partial esophagectomy, cervical, with free intestinal graft, including microvascular anastomosis (43116)',
  },
  {
    category: 'Esophagus Resection',
    name: 'Ivor Lewis-Partial esophagectomy, distal two-thirds, with thoracotomy and separate abdominal incision (43117)',
  },
  {
    category: 'Esophagus Resection',
    name: 'Partial esophagectomy, with thoracotomy and separate abdominal incision with colon interposition or small intestine (43118)',
  },
  {
    category: 'Esophagus Resection',
    name: 'Partial esophagectomy, distal two-thirds, with thoracotomy only (43121)',
  },
  {
    category: 'Esophagus Resection',
    name: 'Thoracoabdominal - Partial esophagectomy, thoracoabdominal approach (43122)',
  },
  {
    category: 'Esophagus Resection',
    name: 'Partial esophagectomy, thoracoabdominal with colon interposition or small intestine (43123)',
  },
  {
    category: 'Esophagus Resection',
    name: 'Total or partial esophagectomy, without reconstruction with cervical esophagostomy (43124)',
  },
  {
    category: 'Esophagus Resection',
    name: 'Minimally invasive three incision esophagectomy (McKeown) (43288)',
  },
  {
    category: 'Esophagus Resection',
    name: 'Minimally invasive esophagectomy, Ivor Lewis approach (43287)',
  },
  {
    category: 'Esophagus Resection',
    name: 'Minimally invasive esophagectomy, Abdominal and neck approach (43286)',
  },
  {
    category: 'Hiatal Hernia/GERD Procedures',
    name: 'Laparoscopy, surgical; esophagogastric fundoplasty (e.g., Nissen, Toupet procedures) (43280)',
  },
  {
    category: 'Hiatal Hernia/GERD Procedures',
    name: 'Laparoscopy, surgical; with repair of paraesophageal hernia (fundoplasty) without mesh (43281)',
  },
  {
    category: 'Hiatal Hernia/GERD Procedures',
    name: 'Laparoscopy, surgical; with repair of paraesophageal hernia (fundoplasty) with mesh (43282)',
  },
  {
    category: 'Hiatal Hernia/GERD Procedures',
    name: 'Nissen fundoplasty - laparotomy (includes partial fundoplication/wrap) (43327)',
  },
  {
    category: 'Hiatal Hernia/GERD Procedures',
    name: 'Transthoracic Fundoplication - open thoracotomy (includes Belsey/Nissen) (43328)',
  },
  {
    category: 'Hiatal Hernia/GERD Procedures',
    name: 'Repair, paraesophageal hiatal hernia via laparotomy without mesh (43332)',
  },
  {
    category: 'Hiatal Hernia/GERD Procedures',
    name: 'Repair, paraesophageal hiatal hernia via laparotomy with mesh (43333)',
  },
  {
    category: 'Hiatal Hernia/GERD Procedures',
    name: 'Repair, paraesophageal hiatal hernia via thoracotomy without mesh (43334)',
  },
  {
    category: 'Hiatal Hernia/GERD Procedures',
    name: 'Repair, paraesophageal hiatal hernia via thoracotomy with mesh (43335)',
  },
  {
    category: 'Hiatal Hernia/GERD Procedures',
    name: 'Repair, paraesophageal hiatal hernia via thoracoabdominal approach without mesh (43336)',
  },
  {
    category: 'Hiatal Hernia/GERD Procedures',
    name: 'Repair, paraesophageal hiatal hernia via thoracoabdominal approach with mesh (43337)',
  },
  { category: 'Tracheal Resection', name: 'Carinal reconstruction (31766)' },
  { category: 'Tracheal Resection', name: 'Excision tracheal stenosis, cervical (31780)' },
  { category: 'Tracheal Resection', name: 'Excision tracheal stenosis, thoracic (31781)' },
  {
    category: 'Tracheal Resection',
    name: 'Tracheal tumor or carcinoma excision, cervical (31785)',
  },
  {
    category: 'Tracheal Resection',
    name: 'Tracheal tumor or carcinoma excision, thoracic (31786)',
  },
  {
    category: 'Thymus/Mediastinal Mass Resection',
    name: 'Thoracoscopy, surgical; with excision of mediastinal cyst, tumor, or mass (32662)',
  },
  {
    category: 'Thymus/Mediastinal Mass Resection',
    name: 'Thymus, resection via Thoracoscopy unilateral or bilateral (32673)',
  },
  {
    category: 'Thymus/Mediastinal Mass Resection',
    name: 'Mediastinal tumor, excision, open, Transthoracic approach (39220)',
  },
  {
    category: 'Thymus/Mediastinal Mass Resection',
    name: 'Thymectomy, transcervical approach (60520)',
  },
  {
    category: 'Thymus/Mediastinal Mass Resection',
    name: 'Thymectomy, transthoracic approach (60521)',
  },
  {
    category: 'Thymus/Mediastinal Mass Resection',
    name: 'Thymectomy, transthoracic approach, with radical mediastinal dissection (60522)',
  },
  { category: 'Trachea, Bronchi, Larynx', name: 'Laryngectomy, partial (31370)' },
  {
    category: 'Trachea, Bronchi, Larynx',
    name: 'Tracheostomy replacement (tube change) prior to est. of fistula tract (31502)',
  },
  { category: 'Trachea, Bronchi, Larynx', name: 'Tracheostomy, planned (31600)' },
  {
    category: 'Trachea, Bronchi, Larynx',
    name: 'Tracheostomy revision simple, without flap (31613)',
  },
  {
    category: 'Trachea, Bronchi, Larynx',
    name: 'Tracheostomy revision complex, with flap (31614)',
  },
  { category: 'Trachea, Bronchi, Larynx', name: 'Tracheoplasty; cervical (31750)' },
  { category: 'Trachea, Bronchi, Larynx', name: 'Tracheoplasty; intrathoracic (31760)' },
  { category: 'Trachea, Bronchi, Larynx', name: 'Bronchoplasty, graft repair (31770)' },
  {
    category: 'Trachea, Bronchi, Larynx',
    name: 'Bronchoplasty; excision stenosis and anastomosis (31775)',
  },
  {
    category: 'Trachea, Bronchi, Larynx',
    name: 'Tracheal wound or injury suture repair; cervical (31800)',
  },
  {
    category: 'Trachea, Bronchi, Larynx',
    name: 'Tracheal wound or injury suture repair; intrathoracic (31805)',
  },
  { category: 'Trachea, Bronchi, Larynx', name: 'Unlisted procedure, trachea, bronchi (31899)' },
  { category: 'Trachea, Bronchi, Larynx', name: 'Bronchopleural fistula closure (32906)' },
  { category: 'Trachea, Bronchi, Larynx', name: 'Bronchogenic cyst removal' },
  { category: 'Trachea, Bronchi, Larynx', name: 'Bronchial laceration suture' },
  { category: 'Trachea, Bronchi, Larynx', name: 'Bronchial sleeve resection' },
  { category: 'Trachea, Bronchi, Larynx', name: 'Tracheostomy mediastinal' },
  { category: 'Trachea, Bronchi, Larynx', name: 'Rigid stent removal' },
  {
    category: 'Bronchoscopy',
    name: 'Tracheobronchoscopy through established tracheostomy incision (31615)',
  },
  {
    category: 'Bronchoscopy',
    name: 'Endobronchial ultrasound (EBUS) during bronchoscopy diagnostic or therapeutic intervention(s) (31620)',
  },
  {
    category: 'Bronchoscopy',
    name: 'Bronchoscopy, diagnostic; with or without cell washing (31622)',
  },
  { category: 'Bronchoscopy', name: 'Bronchoscopy, with brushing or protected brushings (31623)' },
  { category: 'Bronchoscopy', name: 'Bronchoscopy, with bronchial alveolar lavage (BAL) (31624)' },
  {
    category: 'Bronchoscopy',
    name: 'Bronchoscopy, with bronchial or endobronchial biopsy(s), single or multiple sites (31625)',
  },
  { category: 'Bronchoscopy', name: 'Bronchoscopy, with placement of Fiducial markers (31626)' },
  { category: 'Bronchoscopy', name: 'Bronchoscopy, navigational (31627)' },
  {
    category: 'Bronchoscopy',
    name: 'Bronchoscopy, with transbronchial lung biopsy(s), single lobe (31628)',
  },
  {
    category: 'Bronchoscopy',
    name: 'Bronchoscopy, with transbronchial needle aspiration biopsy(s) (31629)',
  },
  {
    category: 'Bronchoscopy',
    name: 'Bronchoscopy, with tracheal/bronchial dilation or closed reduction of fracture (31630)',
  },
  {
    category: 'Bronchoscopy',
    name: 'Bronchoscopy, with placement of tracheal stent(s) (includes tracheal/bronchial dilation as required) (31631)',
  },
  {
    category: 'Bronchoscopy',
    name: 'Bronchoscopy, with transbronchial lung biopsy(s), each additional lobe (31632)',
  },
  {
    category: 'Bronchoscopy',
    name: 'Bronchoscopy, with transbronchial needle aspiration biopsy(s), each additional lobe (31633)',
  },
  { category: 'Bronchoscopy', name: 'Bronchoscopy, with removal of foreign body (31635)' },
  {
    category: 'Bronchoscopy',
    name: 'Bronchoscopy, with placement of bronchial stent(s) (includes tracheal/bronchial dilation as required), initial bronchus (31636)',
  },
  {
    category: 'Bronchoscopy',
    name: 'Bronchoscopy, each additional major bronchus stented (31637)',
  },
  {
    category: 'Bronchoscopy',
    name: 'Bronchoscopy, with revision of tracheal or bronchial stent inserted at previous session (31638)',
  },
  { category: 'Bronchoscopy', name: 'Bronchoscopy, with excision of tumor (31640)' },
  {
    category: 'Bronchoscopy',
    name: 'Bronchoscopy, with destruction of tumor or relief of stenosis by any method other than excision (e.g., laser therapy) (31641)',
  },
  {
    category: 'Bronchoscopy',
    name: 'Bronchoscopy, with placement of catheter(s) for intracavitary radioelement application (31643)',
  },
  {
    category: 'Bronchoscopy',
    name: 'Bronchoscopy, with therapeutic aspiration of tracheobronchial tree, initial (drainage of lung abscess) (31645)',
  },
  {
    category: 'Bronchoscopy',
    name: 'Bronchoscopy, with therapeutic aspiration of tracheobronchial tree, subsequent (31646)',
  },
  {
    category: 'Pleural Space and Lung',
    name: 'Thoracostomy, with rib resection for empyema (32035)',
  },
  {
    category: 'Pleural Space and Lung',
    name: 'Thoracostomy, with open flap drainage for empyema (32036)',
  },
  {
    category: 'Pleural Space and Lung',
    name: 'Thoracotomy, with biopsy(s) lung infiltrate(s) (e.g. wedge), unilateral (32096)',
  },
  {
    category: 'Pleural Space and Lung',
    name: 'Thoracotomy, with biopsy(s) lung nodule(s) or masses (e.g. incisional), unilateral (32097)',
  },
  { category: 'Pleural Space and Lung', name: 'Thoracotomy, with biopsy(s) of pleura (32098)' },
  { category: 'Pleural Space and Lung', name: 'Thoracotomy, with exploration (32100)' },
  {
    category: 'Pleural Space and Lung',
    name: 'Thoracotomy, major; with control of traumatic hemorrhage and/or repair of lung tear (32110)',
  },
  {
    category: 'Pleural Space and Lung',
    name: 'Thoracotomy, major; for postoperative complications (32120)',
  },
  {
    category: 'Pleural Space and Lung',
    name: 'Thoracotomy, with open intrapleural pneumolysis (32124)',
  },
  {
    category: 'Pleural Space and Lung',
    name: 'Thoracotomy, major; with cyst(s) removal, with or without a pleural procedure (32140)',
  },
  {
    category: 'Pleural Space and Lung',
    name: 'Thoracotomy, major; with excision-plication of bullae, with or without any pleural procedure (32141)',
  },
  {
    category: 'Pleural Space and Lung',
    name: 'Thoracotomy, major; with removal of intrapleural foreign body or hematoma (32150)',
  },
  { category: 'Pleural Space and Lung', name: 'Thoracotomy, with cardiac massage (32160)' },
  { category: 'Pleural Space and Lung', name: 'Decortication, pulmonary, partial (32225)' },
  { category: 'Pleural Space and Lung', name: 'Decortication, pulmonary, total (32220)' },
  { category: 'Pleural Space and Lung', name: 'Decortication and parietal pleurectomy (32320)' },
  { category: 'Pleural Space and Lung', name: 'Pleurectomy, parietal (32310)' },
  {
    category: 'Pleural Space and Lung',
    name: 'Pleural scarification for repeat pneumothorax (32215)',
  },
  {
    category: 'Pleural Space and Lung',
    name: 'Removal of lung, excision-plication of emphysematous lung(s) for lung volume reduction (LVRS) (32491)',
  },
  {
    category: 'Pleural Space and Lung',
    name: 'Insertion indwelling tunneled pleural catheter (32550)',
  },
  {
    category: 'Pleural Space and Lung',
    name: 'Thoracoscopy, diagnostic; lungs and pleural space, without biopsy (32601)',
  },
  {
    category: 'Pleural Space and Lung',
    name: 'Thoracoscopy, diagnostic; with biopsy(s) of lung infiltrate(s) (e.g. wedge), unilateral (32607)',
  },
  {
    category: 'Pleural Space and Lung',
    name: 'Thoracoscopy, diagnostic; with biopsy(s) of lung nodule(s) or mass(es) (eg incisional), unilateral (32608)',
  },
  {
    category: 'Pleural Space and Lung',
    name: 'Thoracoscopy, diagnostic; with biopsy(s) of pleura (32609)',
  },
  {
    category: 'Pleural Space and Lung',
    name: 'Thoracoscopy, surgical; with pleurodesis (e.g., mechanical or chemical) (32650)',
  },
  {
    category: 'Pleural Space and Lung',
    name: 'Thoracoscopy, surgical; with partial pulmonary decortication (32651)',
  },
  {
    category: 'Pleural Space and Lung',
    name: 'Thoracoscopy, surgical; with total pulmonary decortication (32652)',
  },
  {
    category: 'Pleural Space and Lung',
    name: 'Thoracoscopy, surgical; with removal of intrapleural foreign body or fibrin deposit (32653)',
  },
  {
    category: 'Pleural Space and Lung',
    name: 'Thoracoscopy, surgical; with control of traumatic hemorrhage (32654)',
  },
  {
    category: 'Pleural Space and Lung',
    name: 'Thoracoscopy, surgical; with excision-plication of bullae, including any pleural procedure (32655)',
  },
  {
    category: 'Pleural Space and Lung',
    name: 'Thoracoscopy, surgical; with parietal pleurectomy (32656)',
  },
  {
    category: 'Pleural Space and Lung',
    name:
      'Thoracoscopy with resection-plication for emphysematous lung (bullous or non-bullous) for lung volume reduction- LVRS, unilateral including any pleural procedure (32672)',
  },
  { category: 'Pleural Space and Lung', name: 'Repair lung hernia through chest wall (32800)' },
  {
    category: 'Pleural Space and Lung',
    name: 'Closure of chest wall following open flap drainage for empyema (Clagett type procedure) (32810)',
  },
  {
    category: 'Pleural Space and Lung',
    name: 'Total lung lavage (for alveolar proteinosis) (32997)',
  },
  { category: 'Pleural Space and Lung', name: 'Radio-frequency ablation (RFA) lung tumor (32998)' },
  {
    category: 'Pleural Space and Lung',
    name: 'Removal of lung, total pneumonectomy; extrapleural (32445)',
  },
  { category: 'Pleural Space and Lung', name: 'Unlisted procedure, lung (32999)' },
  { category: 'Lung Other Procedures', name: 'Open closure of major bronchial fistula (32815)' },
  { category: 'Lung Other Procedures', name: 'Single lung transplant (32851)' },
  { category: 'Lung Other Procedures', name: 'Single lung transplant with CPB (32852)' },
  { category: 'Lung Other Procedures', name: 'Double lung transplant (32853)' },
  { category: 'Lung Other Procedures', name: 'Double lung transplant with CPB (32854)' },
  { category: 'Lung Other Procedures', name: 'Thoracoplasty with closure of bronchopleural fistula (32906)' },
  { category: 'Mediastinum and Diaphragm', name: 'Thoracoscopy, diagnostic; mediastinal space, with biopsy (32606)' },
  { category: 'Mediastinum and Diaphragm', name: 'Mediastinotomy with exploration or biopsy; cervical approach (39000)' },
  { category: 'Mediastinum and Diaphragm', name: 'Mediastinotomy with exploration or biopsy; transthoracic approach (39010)' },
  { category: 'Mediastinum and Diaphragm', name: 'Mediastinal cyst, excision, open, Transthoracic approach (39200)' },
  { category: 'Mediastinum and Diaphragm', name: 'Mediastinoscopy, with or without biopsy (39400)' },
  { category: 'Mediastinum and Diaphragm', name: 'Unlisted procedure, mediastinum (39499)' },
  { category: 'Mediastinum and Diaphragm', name: 'Diaphragm, laceration repair, any approach (39501)' },
  { category: 'Mediastinum and Diaphragm', name: 'Diaphragmatic hernia repair (other than neonatal), traumatic; acute (39540)' },
  { category: 'Mediastinum and Diaphragm', name: 'Diaphragmatic hernia repair (other than neonatal), traumatic; chronic (39541)' },
  { category: 'Mediastinum and Diaphragm', name: 'Diaphragm imbrication (i.e., plication) of (39545)' },
  { category: 'Mediastinum and Diaphragm', name: 'Diaphragm; resection with simple repair (e.g., primary suture) (39560)' },
  {
    category: 'Mediastinum and Diaphragm',
    name: 'Diaphragm; resection with complex repair (e.g., prosthetic material, local muscle flap) (39561)',
  },
  { category: 'Mediastinum and Diaphragm', name: 'Unlisted procedure, diaphragm (39599)' },
  { category: 'Esophagoscopy', name: 'Esophagoscopy (43200)' },
  { category: 'Esophagoscopy', name: 'Esophagoscopy with biopsy (43202)' },
  { category: 'Esophagoscopy', name: 'Esophagoscopy with removal of foreign body (43215)' },
  { category: 'Esophagoscopy', name: 'Esophagoscopy with insertion of stent (43219)' },
  { category: 'Esophagoscopy', name: 'Esophagoscopy with balloon dilation (43220)' },
  { category: 'Esophagoscopy', name: 'Esophagoscopy with insertion of guide wire followed by dilation over guide wire (43226)' },
  { category: 'Esophagoscopy', name: 'Esophagoscopy with ablation of tumor (43228)' },
  { category: 'Esophagoscopy', name: 'Esophagoscopy with endoscopic ultrasound examination (EUS) (43231)' },
  { category: 'Esophagoscopy', name: 'Esophagoscopy with transendoscopic ultrasound-guided fine needle aspiration (43232)' },
  { category: 'Esophagoscopy', name: 'Upper gastrointestinal endoscopy, diagnostic (43235)' },
  {
    category: 'Esophagoscopy',
    name: 'Upper gastrointestinal endoscopy with endoscopic ultrasound examination limited to the esophagus (43237)',
  },
  { category: 'Esophagoscopy', name: 'Upper gastrointestinal endoscopy with transendoscopic ultrasound- guided FNA (43238)' },
  { category: 'Esophagoscopy', name: 'Upper gastrointestinal endoscopy with biopsy (43239)' },
  { category: 'Esophagoscopy', name: 'Upper gastrointestinal endoscopy with dilation of gastric outlet for obstruction (43245)' },
  { category: 'Esophagoscopy', name: 'Upper gastrointestinal endoscopy with directed placement of percutaneous gastrostomy tube (43246)' },
  { category: 'Esophagoscopy', name: 'Upper gastrointestinal endoscopy with removal of foreign body (43247)' },
  {
    category: 'Esophagoscopy',
    name: 'Upper gastrointestinal endoscopy with insertion of guide wire followed by dilation of esophagus (43248)',
  },
  { category: 'Esophagoscopy', name: 'Upper gastrointestinal endoscopy with balloon dilation of esophagus (43249)' },
  { category: 'Esophagoscopy', name: 'Upper gastrointestinal endoscopy with transendoscopic stent placement (43256)' },
  { category: 'Esophagoscopy', name: 'Upper gastrointestinal endoscopy with ablation of tumor (43258)' },
  { category: 'Esophagus Other Procedures', name: 'Thoracoscopy, surgical; with esophagomyotomy (Heller type) (32665)' },
  { category: 'Esophagus Other Procedures', name: 'Cricopharyngeal myotomy (43030)' },
  { category: 'Esophagus Other Procedures', name: 'Excision esophageal lesion with primary repair, cervical approach (43100)' },
  {
    category: 'Esophagus Other Procedures',
    name: 'Excision esophageal lesion with primary repair, thoracic approach (e.g., leiomyoma) (43101)',
  },
  {
    category: 'Esophagus Other Procedures',
    name: 'Diverticulectomy of hypopharynx or esophagus, with or without myotomy; cervical approach (43130)',
  },
  { category: 'Esophagus Other Procedures', name: 'Diverticulectomy of esophagus, with or without myotomy; thoracic approach (43135)' },
  { category: 'Esophagus Other Procedures', name: 'Esophagostomy, fistulization of esophagus, external; cervical approach (43352)' },
  { category: 'Esophagus Other Procedures', name: 'Gastrointestinal reconstruction for previous esophagectomy with stomach (43360)' },
  {
    category: 'Esophagus Other Procedures',
    name: 'Gastrointestinal reconstruction for previous esophagectomy with colon interposition or small intestine (43361)',
  },
  { category: 'Esophagus Other Procedures', name: 'Suture of esophageal wound or injury; cervical approach (43410)' },
  {
    category: 'Esophagus Other Procedures',
    name: 'Suture of esophageal wound or injury; transthoracic or transabdominal approach (43415)',
  },
  { category: 'Esophagus Other Procedures', name: 'Closure of esophagostomy or fistula; cervical approach (43420)' },
  {
    category: 'Esophagus Other Procedures',
    name: 'Laparoscopic esophageal myotomy (Heller Myotomy, with or without fundoplication) (43279)',
  },
  { category: 'Esophagus Other Procedures', name: 'Laparoscopy, surgical, esophageal lengthening procedure (Collis) (43283)' },
  { category: 'Esophagus Other Procedures', name: 'Unlisted laparoscopy, esophagus (43289)' },
  { category: 'Esophagus Other Procedures', name: 'Esophagoplasty with repair of TEF, cervical approach (43305)' },
  { category: 'Esophagus Other Procedures', name: 'Esophagoplasty with repair TEF, thoracic approach (43312)' },
  { category: 'Esophagus Other Procedures', name: 'Esophagomyotomy (Heller type); thoracic approach (43331)' },
  { category: 'Esophagus Other Procedures', name: 'Free jejunum transfer with microvascular anastomosis (43496)' },
  { category: 'Esophagus Other Procedures', name: 'Unlisted procedure, esophagus (43499)' },
  { category: 'Esophagus Other Procedures', name: 'Total gastrectomy with esophagoenterostomy (43620)' },
  { category: 'Esophagus Other Procedures', name: 'Total gastrectomy with Roux-en-Y reconstruction (43621)' },
  { category: 'Esophagus Other Procedures', name: 'Conduit revision s/p esophagectomy' },
  { category: 'Esophagus Other Procedures', name: 'Per oral endoscopic myotomy (POEM)' },
  { category: 'Esophagus Other Procedures', name: 'Trans oral fundoplication' },
  { category: 'Esophagus Other Procedures', name: 'Esophageal lengthening procedure - open (Collis) Secondary Procedure code (43338)' },
  { category: 'Esophagus Other Procedures', name: 'Ligation or stapling at gastroesophageal junction for esophageal perforation (43405)' },
  { category: 'Chest Wall and Neck', name: 'Muscle flap, neck (15732)' },
  { category: 'Chest Wall and Neck', name: 'Muscle flap, trunk (i.e., intercostal, pectoralis or serratus muscle) (15734)' },
  { category: 'Chest Wall and Neck', name: 'Excision of chest wall tumor including ribs (19260)' },
  { category: 'Chest Wall and Neck', name: 'Excision of chest wall tumor involving ribs, with reconstruction (19271)' },
  { category: 'Chest Wall and Neck', name: 'Excision tumor, soft tissue of neck or thorax; subcutaneous (21555)' },
  { category: 'Chest Wall and Neck', name: 'Excision tumor, soft tissue of neck or thorax; deep, subfascial, intramuscular (21556)' },
  { category: 'Chest Wall and Neck', name: 'Radical resection of tumor (e.g., malignant neoplasm), soft tissue of neck or thorax (21557)' },
  { category: 'Chest Wall and Neck', name: 'Excision of rib, partial (21600)' },
  { category: 'Chest Wall and Neck', name: 'Excision first and/or cervical rib (21615)' },
  { category: 'Chest Wall and Neck', name: 'Excision first and/or cervical rib; with sympathectomy (21616)' },
  { category: 'Chest Wall and Neck', name: 'Major reconstruction, chest wall (posttraumatic) (32820)' },
  { category: 'Chest Wall and Neck', name: 'Radical resection of sternum (21630)' },
  { category: 'Chest Wall and Neck', name: 'Radical resection of sternum; with mediastinal lymphadenectomy (21632)' },
  { category: 'Chest Wall and Neck', name: 'Hyoid myotomy and suspension (21685)' },
  { category: 'Chest Wall and Neck', name: 'Division of scalenus anticus; without resection of cervical rib (21700)' },
  { category: 'Chest Wall and Neck', name: 'Division of scalenus anticus; with resection of cervical rib (21705)' },
  { category: 'Chest Wall and Neck', name: 'Reconstructive repair of pectus excavatum or carinatum; open (21740)' },
  {
    category: 'Chest Wall and Neck',
    name: 'Reconstructive repair of pectus, minimally invasive approach (Nuss procedure), without thoracoscopy (21742)',
  },
  { category: 'Chest Wall and Neck', name: 'Open treatment of sternum fracture with or without skeletal fixation (21825)' },
  { category: 'Chest Wall and Neck', name: 'Removal of sternal wire(s)' },
  {
    category: 'Chest Wall and Neck',
    name: 'Reconstructive repair of pectus, minimally invasive approach (Nuss procedure), with thoracoscopy (21743)',
  },
  { category: 'Chest Wall and Neck', name: 'Unlisted procedure, neck or thorax (21899)' },
  { category: 'Miscellaneous', name: 'Thoracoscopy, diagnostic pericardial sac, with biopsy (32604)' },
  { category: 'Miscellaneous', name: 'Thoracoscopy, surgical; with removal of clot or foreign body from pericardial sac (32658)' },
  {
    category: 'Miscellaneous',
    name: 'Thoracoscopy, surgical; with creation of pericardial window or partial resection of pericardial sac for drainage (32659)',
  },
  { category: 'Miscellaneous', name: 'Thoracoscopy, surgical; with total pericardiectomy (32660)' },
  { category: 'Miscellaneous', name: 'Thoracoscopy, surgical; with excision of pericardial cyst, tumor, or mass (32661)' },
  { category: 'Miscellaneous', name: 'Thoracoscopy, surgical; with thoracic sympathectomy (32664)' },
  {
    category: 'Miscellaneous',
    name: 'Stereotactic radiosurgery (SRS) and stereotactic body radiotherapy (SBRT),surgeon participation (32701)',
  },
  { category: 'Miscellaneous', name: 'Tube pericardiostomy (33015)' },
  { category: 'Miscellaneous', name: 'SVC resection and reconstruction (34502)' },
  { category: 'Miscellaneous', name: 'Ligation thoracic duct (38381)' },
  { category: 'Miscellaneous', name: 'Intraoperative jejunostomy (44015)' },
  { category: 'Miscellaneous', name: 'Omental flap (49904)' },
  { category: 'Miscellaneous', name: 'Transthoracic thyroidectomy (60270)' },
  { category: 'Miscellaneous', name: 'Removal substernal thyroid, cervical approach (60271)' },
  { category: 'Miscellaneous', name: 'Application of wound vac (97605, 97606)' },
  { category: 'Miscellaneous', name: 'Pericardial window (33025)' },
  { category: 'Miscellaneous', name: 'Other Minor Procedure' },
  { category: 'Miscellaneous', name: 'Other' },
];
