import { FormConditions } from 'src/app/shared/modules/registry-form/registry-form.model';

export const Gtsd241Conditions: FormConditions = {
  sectionA: [{ control: 'ZipCode', parentControl: 'PermAddr', conditions: ['Yes'] }],
  sectionB: [{ control: 'AdmitDt', parentControl: 'AdmissionStat', conditions: ['Inpatient'] }],
  sectionC: [
    { control: 'EF', parentControl: 'CHF', conditions: ['Yes'] },
    { control: 'VHDLocAV', parentControl: 'VHD', conditions: ['Yes'] },
    { control: 'VHDLocMV', parentControl: 'VHD', conditions: ['Yes'] },
    { control: 'VHDLocPV', parentControl: 'VHD', conditions: ['Yes'] },
    { control: 'VHDLocTV', parentControl: 'VHD', conditions: ['Yes'] },
    { control: 'PNI', parentControl: 'CerebroHx', conditions: ['CerebrovascularAccident (CVA)'] },
    { control: 'DiabCtrl', parentControl: 'Diabetes', conditions: ['Yes'] },
    { control: 'PreopChemoCurWhen', parentControl: 'PreopChemoCur', conditions: ['Yes'] },
    { control: 'PreopXRTDisWhen', parentControl: 'PreopXRT', conditions: ['Yes'] },
    {
      control: 'PreopXRTCompDt',
      parentControl: 'PreopXRTDisWhen',
      conditions: ['Same disease, <= 6 months'],
    },
    { control: 'PriorStern', parentControl: 'PriorCTS', conditions: ['Yes'] },
    { control: 'PriorVATS', parentControl: 'PriorCTS', conditions: ['Yes'] },
    { control: 'PriorVATSLoc', parentControl: 'PriorVATS', conditions: ['Yes'] },
    { control: 'PriorPulmRes', parentControl: 'PriorCTS', conditions: ['Yes'] },
    { control: 'PriorPulmResLoc', parentControl: 'PriorPulmRes', conditions: ['Yes'] },
    { control: 'PriorThora', parentControl: 'PriorCTS', conditions: ['Yes'] },
    { control: 'PriorThoraLoc', parentControl: 'PriorThora', conditions: ['Yes'] },
    { control: 'CreatLst', parentControl: 'CreatMeasured', conditions: ['Yes'] },
    { control: 'HemoglobinLst', parentControl: 'HemoglobinMeasured', conditions: ['Yes'] },
    { control: 'PFTNotPerReas', parentControl: 'PFT', conditions: ['No'] },
    { control: 'FEV', parentControl: 'PFT', conditions: ['Yes'] },
    { control: 'FEVPred', parentControl: 'FEV', conditions: ['Yes'] },
    { control: 'DLCO', parentControl: 'PFT', conditions: ['Yes'] },
    { control: 'DLCOPred', parentControl: 'DLCO', conditions: ['Yes'] },
    {
      control: 'PackYearKnown',
      parentControl: 'CigSmoking',
      conditions: ['Past smoker', 'Current smoker'],
    },
    { control: 'PackYear', parentControl: 'PackYearKnown', conditions: ['Yes'] },
  ],
  sectionD: [],
  sectionE: [
    {
      control: 'UnanticConvTy',
      parentControl: 'UnanticConv',
      conditions: ['!', 'No'],
    },
    {
      control: 'UnanticConvRsn',
      parentControl: 'UnanticConv',
      conditions: ['!', 'No'],
    },
    { control: 'IntraopPRBCNum', parentControl: 'IntraopPRBC', conditions: ['Yes'] },
  ],
  sectionF: [
    { control: 'sectionFBody', parentControl: 'sectionE:LungCancer', conditions: ['Yes'] },
    { control: 'LungCancerSus', parentControl: 'sectionE:LungCancer', conditions: ['Yes'] },
    { control: 'ClinStagLungBronc', parentControl: 'sectionE:LungCancer', conditions: ['Yes'] },
    { control: 'ClinStagLungNeedle', parentControl: 'sectionE:LungCancer', conditions: ['Yes'] },
    { control: 'ClinStagDoneLung', parentControl: 'sectionE:LungCancer', conditions: ['Yes'] },
    { control: 'PreopPosTisOb', parentControl: 'ClinStagDoneLung', conditions: ['Yes'] },
    { control: 'ClinStagLungPET', parentControl: 'ClinStagDoneLung', conditions: ['Yes'] },
    { control: 'ClinStagLungCT', parentControl: 'ClinStagDoneLung', conditions: ['Yes'] },
    { control: 'ClinStagLungBrainCT', parentControl: 'ClinStagDoneLung', conditions: ['Yes'] },
    { control: 'ClinStagLungBMRI', parentControl: 'ClinStagDoneLung', conditions: ['Yes'] },
    { control: 'ClinStagInvasive', parentControl: 'ClinStagDoneLung', conditions: ['Yes'] },
    { control: 'ClinStagInvasiveSize', parentControl: 'ClinStagInvasive', conditions: ['Yes, reason documented'] },
    { control: 'ClinStagInvasiveLymphCT', parentControl: 'ClinStagInvasive', conditions: ['Yes, reason documented'] },
    { control: 'ClinStagInvasiveHilar', parentControl: 'ClinStagInvasive', conditions: ['Yes, reason documented'] },
    { control: 'ClinStagInvasiveTumor', parentControl: 'ClinStagInvasive', conditions: ['Yes, reason documented'] },
    { control: 'ClinStagInvasiveOther', parentControl: 'ClinStagInvasive', conditions: ['Yes, reason documented'] },
    { control: 'ClinStagLungEBUS', parentControl: 'ClinStagDoneLung', conditions: ['Yes'] },
    { control: 'ClinStagLungEUS', parentControl: 'ClinStagDoneLung', conditions: ['Yes'] },
    { control: 'ClinStagLungMedia', parentControl: 'ClinStagDoneLung', conditions: ['Yes'] },
    { control: 'ClinStagLungVATS', parentControl: 'ClinStagDoneLung', conditions: ['Yes'] },
    { control: 'ClinStagLungOth', parentControl: 'ClinStagDoneLung', conditions: ['Yes'] },
    { control: 'LungCaTumSzKnown', parentControl: 'ClinStagDoneLung', conditions: ['Yes'] },
    { control: 'LungCaTumSz', parentControl: 'LungCaTumSzKnown', conditions: ['Yes'] },
    { control: 'LCInvAdjStr', parentControl: 'ClinStagDoneLung', conditions: ['Yes'] },
    { control: 'ClinStageLungTumor', parentControl: 'ClinStagDoneLung', conditions: ['Yes'] },
    { control: 'ClinStageLungN', parentControl: 'ClinStagDoneLung', conditions: ['Yes'] },
    { control: 'ClinStageLungM', parentControl: 'ClinStagDoneLung', conditions: ['Yes'] },
    { control: 'ClinStageLungResult', parentControl: 'sectionE:LungCancer', conditions: ['Yes'] },
    { control: 'PathStageLungT', parentControl: 'ClinStageLungResult', conditions: ['Lung Cancer Tumor present'] },
    { control: 'VisPleuraInv', parentControl: 'PathStageLungT', conditions: ['T2a', 'T2b'] },
    { control: 'PathStageLungN', parentControl: 'ClinStageLungResult', conditions: ['Lung Cancer Tumor present'] },
    { control: 'PathStageLungMultiN2', parentControl: 'PathStageLungN', conditions: ['N2'] },
    { control: 'PathStageLungM', parentControl: 'ClinStageLungResult', conditions: ['Lung Cancer Tumor present'] },
    { control: 'LungCAHist', parentControl: 'ClinStageLungResult', conditions: ['Lung Cancer Tumor present'] },
    { control: 'LungCAHistGrade', parentControl: 'ClinStageLungResult', conditions: ['Lung Cancer Tumor present'] },
    { control: 'LungCANodes', parentControl: 'ClinStageLungResult', conditions: ['Lung Cancer Tumor present'] },
    { control: 'LungCANodStat', parentControl: 'ClinStageLungResult', conditions: ['Lung Cancer Tumor present'] },
    { control: 'LungCAPathMarg', parentControl: 'ClinStageLungResult', conditions: ['Lung Cancer Tumor present'] },
    { control: 'LungCAPathMargPosR', parentControl: 'LungCAPathMarg', conditions: ['Yes'] },
  ],
  sectionG: [
    { control: 'sectionGBody', parentControl: 'sectionE:EsophCancer', conditions: ['Yes'] },
    { control: 'ClinStagDoneEsoph', parentControl: 'sectionE:EsophCancer', conditions: ['Yes'] },
    { control: 'ClinStagEsophPET', parentControl: 'ClinStagDoneEsoph', conditions: ['Yes'] },
    { control: 'ClinStagEsophCT', parentControl: 'ClinStagDoneEsoph', conditions: ['Yes'] },
    { control: 'ClinStagEsophBronc', parentControl: 'ClinStagDoneEsoph', conditions: ['Yes'] },
    { control: 'ClinStagEsophEUS', parentControl: 'ClinStagDoneEsoph', conditions: ['Yes'] },
    { control: 'ClinStagEsophVATS', parentControl: 'ClinStagDoneEsoph', conditions: ['Yes'] },
    { control: 'ClinStagEsophLap', parentControl: 'ClinStagDoneEsoph', conditions: ['Yes'] },
    { control: 'ClinStagEsophEMR', parentControl: 'ClinStagDoneEsoph', conditions: ['Yes'] },
    { control: 'ClinStagEsophOth', parentControl: 'ClinStagDoneEsoph', conditions: ['Yes'] },
    { control: 'ClinStageEsophT', parentControl: 'ClinStagDoneEsoph', conditions: ['Yes'] },
    { control: 'ClinStageEsophNode', parentControl: 'ClinStagDoneEsoph', conditions: ['Yes'] },
    { control: 'ClinStageEsophM', parentControl: 'ClinStagDoneEsoph', conditions: ['Yes'] },
    { control: 'TumorEsopCervical', parentControl: 'ClinStagDoneEsoph', conditions: ['Yes'] },
    { control: 'TumorEsopUpThorac', parentControl: 'ClinStagDoneEsoph', conditions: ['Yes'] },
    { control: 'TumorEsopMidThorac', parentControl: 'ClinStagDoneEsoph', conditions: ['Yes'] },
    { control: 'TumorEsopLowThorac', parentControl: 'ClinStagDoneEsoph', conditions: ['Yes'] },
    { control: 'ClinStageEsophResult', parentControl: 'sectionE:EsophCancer', conditions: ['Yes'] },
    { control: 'PathStageEsophT', parentControl: 'ClinStageEsophResult', conditions: ['Esophageal cancer present'] },
    { control: 'PathStageEsophN', parentControl: 'ClinStageEsophResult', conditions: ['Esophageal cancer present'] },
    { control: 'PathStageEsophM', parentControl: 'ClinStageEsophResult', conditions: ['Esophageal cancer present'] },
    { control: 'PathStageEsophH', parentControl: 'ClinStageEsophResult', conditions: ['Esophageal cancer present'] },
    { control: 'PathStageEsophG', parentControl: 'ClinStageEsophResult', conditions: ['Esophageal cancer present'] },
    { control: 'EsophCANodes', parentControl: 'ClinStageEsophResult', conditions: ['Esophageal cancer present'] },
    { control: 'EsophCAPathMarg', parentControl: 'ClinStageEsophResult', conditions: ['Esophageal cancer present'] },
  ],
  sectionH: [
    { control: 'sectionHBody', parentControl: 'sectionE:ThymusMediastinalData', conditions: ['Yes'] },
    { control: 'MyastheniaSympt', parentControl: 'sectionE:ThymusMediastinalData', conditions: ['Yes'] },
    { control: 'TxMestinon', parentControl: 'MyastheniaSympt', conditions: ['Yes'] },
    { control: 'TxSteroids', parentControl: 'MyastheniaSympt', conditions: ['Yes'] },
    { control: 'TxImmunoSuppress', parentControl: 'MyastheniaSympt', conditions: ['Yes'] },
    { control: 'IVIG', parentControl: 'sectionE:ThymusMediastinalData', conditions: ['Yes'] },
    { control: 'Plasmaphereis', parentControl: 'sectionE:ThymusMediastinalData', conditions: ['Yes'] },
    { control: 'MassSizeKnown', parentControl: 'sectionE:ThymusMediastinalData', conditions: ['Yes'] },
    { control: 'MassSize', parentControl: 'MassSizeKnown', conditions: ['Yes'] },
    { control: 'ThyInitSurgAp', parentControl: 'sectionE:ThymusMediastinalData', conditions: ['Yes'] },
    { control: 'ThyRobVATSLoc', parentControl: 'ThyInitSurgAp', conditions: ['Robotic', 'VATS'] },
    { control: 'ThyConvToOpen', parentControl: 'ThyInitSurgAp', conditions: ['Transcervical', 'Partial Sternotomy', 'Robotic', 'VATS'] },
    { control: 'ThyConvAp', parentControl: 'ThyConvToOpen', conditions: ['Yes, planned', 'Yes, unplanned'] },
    { control: 'PhrenicNerveResect', parentControl: 'sectionE:ThymusMediastinalData', conditions: ['Yes'] },
    { control: 'PathRptStage', parentControl: 'sectionE:ThymusMediastinalData', conditions: ['Yes'] },
    { control: 'ThymomaType', parentControl: 'sectionE:ThymusMediastinalData', conditions: ['Yes'] },
    { control: 'ResectCompleteness', parentControl: 'sectionE:ThymusMediastinalData', conditions: ['Yes'] },
    { control: 'PtAlive30Day', parentControl: 'sectionE:ThymusMediastinalData', conditions: ['Yes'] },
    { control: 'MYAL', parentControl: 'PtAlive30Day', conditions: ['Yes'] },
    { control: 'PhrenicNervePalsy', parentControl: 'PtAlive30Day', conditions: ['Yes'] },
    { control: 'PtAlive90Day', parentControl: 'sectionE:ThymusMediastinalData', conditions: ['Yes'] },
    { control: 'ThoracicRadiation', parentControl: 'PtAlive90Day', conditions: ['Yes'] },
    { control: 'PhrenNrvPalsyPersis', parentControl: 'PtAlive90Day', conditions: ['Yes'] },
  ],
  sectionI: [
    { control: 'sectionIBody', parentControl: 'sectionE:TrachealData', conditions: ['Yes'] },
    { control: 'AirwayCurr', parentControl: 'sectionE:TrachealData', conditions: ['Yes'] },
    { control: 'TracheostomyPrior', parentControl: 'sectionE:TrachealData', conditions: ['Yes'] },
    { control: 'IntubatePrior', parentControl: 'sectionE:TrachealData', conditions: ['Yes'] },
    { control: 'TrachealResectPrior', parentControl: 'sectionE:TrachealData', conditions: ['Yes'] },
    { control: 'BronchInt6Wks', parentControl: 'sectionE:TrachealData', conditions: ['Yes'] },
    { control: 'RecurrNervesIntact', parentControl: 'sectionE:TrachealData', conditions: ['Yes'] },
    { control: 'RecurrNervNotIntact', parentControl: 'RecurrNervesIntact', conditions: ['Yes'] },
    { control: 'CrossTableVent', parentControl: 'sectionE:TrachealData', conditions: ['Yes'] },
    { control: 'JetVent', parentControl: 'sectionE:TrachealData', conditions: ['Yes'] },
    { control: 'VvECMO', parentControl: 'sectionE:TrachealData', conditions: ['Yes'] },
    { control: 'VaECMO', parentControl: 'sectionE:TrachealData', conditions: ['Yes'] },
    { control: 'CardoPulmBypass', parentControl: 'sectionE:TrachealData', conditions: ['Yes'] },
    { control: 'TrachIncisCerv', parentControl: 'sectionE:TrachealData', conditions: ['Yes'] },
    { control: 'TrachIncisRight', parentControl: 'sectionE:TrachealData', conditions: ['Yes'] },
    { control: 'TrachIncisClam', parentControl: 'sectionE:TrachealData', conditions: ['Yes'] },
    { control: 'TrachIncisPartStern', parentControl: 'sectionE:TrachealData', conditions: ['Yes'] },
    { control: 'TrachIncisFullStern', parentControl: 'sectionE:TrachealData', conditions: ['Yes'] },
    { control: 'TrachealResectLen', parentControl: 'sectionE:TrachealData', conditions: ['Yes'] },
    { control: 'CricoidResect', parentControl: 'sectionE:TrachealData', conditions: ['Yes'] },
    { control: 'CarinalResect', parentControl: 'sectionE:TrachealData', conditions: ['Yes'] },
    { control: 'ReleaseManeuver', parentControl: 'sectionE:TrachealData', conditions: ['Yes'] },
    { control: 'ReleaseManeuverType', parentControl: 'ReleaseManeuver', conditions: ['Yes'] },
    { control: 'AnastomoticDehiscen', parentControl: 'sectionE:TrachealData', conditions: ['Yes'] },
    { control: 'AnastomoticStricture', parentControl: 'sectionE:TrachealData', conditions: ['Yes'] },
    { control: 'AirwayObstruct', parentControl: 'sectionE:TrachealData', conditions: ['Yes'] },
    { control: 'NervePalsyRecurr', parentControl: 'sectionE:TrachealData', conditions: ['Yes'] },
    { control: 'TrachealAppliance', parentControl: 'sectionE:TrachealData', conditions: ['Yes'] },
    { control: 'StentTubeFree30days', parentControl: 'sectionE:TrachealData', conditions: ['Yes'] },
    { control: 'StentTubeFree90days', parentControl: 'sectionE:TrachealData', conditions: ['Yes'] },
  ],
  sectionJ: [
    { control: 'sectionJBody', parentControl: 'sectionE:HiatalHerniaData', conditions: ['Yes'] },
    { control: 'Heartburn', parentControl: 'sectionE:HiatalHerniaData', conditions: ['Yes'] },
    { control: 'Cough', parentControl: 'sectionE:HiatalHerniaData', conditions: ['Yes'] },
    { control: 'Regurgitate', parentControl: 'sectionE:HiatalHerniaData', conditions: ['Yes'] },
    { control: 'Hoarse', parentControl: 'sectionE:HiatalHerniaData', conditions: ['Yes'] },
    { control: 'Dysphagia', parentControl: 'sectionE:HiatalHerniaData', conditions: ['Yes'] },
    { control: 'SoreThroat', parentControl: 'sectionE:HiatalHerniaData', conditions: ['Yes'] },
    { control: 'Ephigastric', parentControl: 'sectionE:HiatalHerniaData', conditions: ['Yes'] },
    { control: 'Asthma', parentControl: 'sectionE:HiatalHerniaData', conditions: ['Yes'] },
    { control: 'EarlySatiety', parentControl: 'sectionE:HiatalHerniaData', conditions: ['Yes'] },
    { control: 'RefluxLaryngitis', parentControl: 'sectionE:HiatalHerniaData', conditions: ['Yes'] },
    { control: 'Anemia', parentControl: 'sectionE:HiatalHerniaData', conditions: ['Yes'] },
    { control: 'PPIUse', parentControl: 'sectionE:HiatalHerniaData', conditions: ['Yes'] },
    { control: 'PPIRelief', parentControl: 'PPIUse', conditions: ['Yes'] },
    { control: 'Esophagitis', parentControl: 'sectionE:HiatalHerniaData', conditions: ['Yes'] },
    { control: 'LAGrade', parentControl: 'Esophagitis', conditions: ['Yes'] },
    { control: 'MetaplasiaBarrett', parentControl: 'sectionE:HiatalHerniaData', conditions: ['Yes'] },
    { control: 'pHTest', parentControl: 'sectionE:HiatalHerniaData', conditions: ['Yes'] },
    { control: 'DeMeesterScore', parentControl: 'pHTest', conditions: ['Yes'] },
    { control: 'Manometry', parentControl: 'sectionE:HiatalHerniaData', conditions: ['Yes'] },
    { control: 'Motility', parentControl: 'Manometry', conditions: ['Yes'] },
    { control: 'RestPressure', parentControl: 'sectionE:HiatalHerniaData', conditions: ['Yes'] },
    { control: 'SwallowFail', parentControl: 'sectionE:HiatalHerniaData', conditions: ['Yes'] },
    { control: 'ImagePerform', parentControl: 'sectionE:HiatalHerniaData', conditions: ['Yes'] },
    { control: 'ImageType', parentControl: 'ImagePerform', conditions: ['Yes'] },
    { control: 'HerniaSize', parentControl: 'sectionE:HiatalHerniaData', conditions: ['Yes'] },
    { control: 'HerniaType', parentControl: 'sectionE:HiatalHerniaData', conditions: ['Yes'] },
    { control: 'HerniaRepStat', parentControl: 'sectionE:HiatalHerniaData', conditions: ['Yes'] },
    { control: 'HerniaReopApp', parentControl: 'HerniaRepStat', conditions: ['Re-operation'] },
    { control: 'GERDAppLaparoscop', parentControl: 'sectionE:HiatalHerniaData', conditions: ['Yes'] },
    { control: 'GERDAppRobotic', parentControl: 'sectionE:HiatalHerniaData', conditions: ['Yes'] },
    { control: 'GERDAppLaparotomy', parentControl: 'sectionE:HiatalHerniaData', conditions: ['Yes'] },
    { control: 'GERDAppThor', parentControl: 'sectionE:HiatalHerniaData', conditions: ['Yes'] },
    { control: 'ProcFundoplicate', parentControl: 'sectionE:HiatalHerniaData', conditions: ['Yes'] },
    { control: 'FundoplicateType', parentControl: 'ProcFundoplicate', conditions: ['Yes'] },
    { control: 'ProcGastroplasty', parentControl: 'sectionE:HiatalHerniaData', conditions: ['Yes'] },
    { control: 'ProcMesh', parentControl: 'sectionE:HiatalHerniaData', conditions: ['Yes'] },
    { control: 'ProcRelaxIncision', parentControl: 'sectionE:HiatalHerniaData', conditions: ['Yes'] },
    { control: 'GERDPtAliveMth', parentControl: 'sectionE:HiatalHerniaData', conditions: ['Yes'] },
    { control: 'RadiographRecurr1Mon', parentControl: 'GERDPtAliveMth', conditions: ['Yes'] },
    { control: 'SymptomRecurr1Mon', parentControl: 'GERDPtAliveMth', conditions: ['Yes'] },
    { control: 'EndoInt1Mon', parentControl: 'GERDPtAliveMth', conditions: ['Yes'] },
    { control: 'RedoOperate1Mon', parentControl: 'GERDPtAliveMth', conditions: ['Yes'] },
    { control: 'GERDPtAliveYr', parentControl: 'sectionE:HiatalHerniaData', conditions: ['Yes'] },
    { control: 'RadiographRecurr1Year', parentControl: 'GERDPtAliveYr', conditions: ['Yes'] },
    { control: 'SymptomRecurr1Year', parentControl: 'GERDPtAliveYr', conditions: ['Yes'] },
    { control: 'EndoInt1Year', parentControl: 'GERDPtAliveYr', conditions: ['Yes'] },
    { control: 'RedoOperate1Year', parentControl: 'GERDPtAliveYr', conditions: ['Yes'] },
  ],
  sectionK: [
    { control: 'ICUVisitInitDays', parentControl: 'ICUVisitInit', conditions: ['Yes'] },
    { control: 'ICUVisitAdd', parentControl: 'ICUVisitInit', conditions: ['Yes'] },
    { control: 'ICUVisitAddDays', parentControl: 'ICUVisitAdd', conditions: ['Yes'] },
  ],
  sectionL: [
    { control: 'PostOpInvProc', parentControl: 'POEvents', conditions: ['Yes'] },
    { control: 'ReturnORRsn', parentControl: 'PostOpInvProc', conditions: ['Yes'] },
    { control: 'PosOpProcAL', parentControl: 'PostOpInvProc', conditions: ['Yes'] },
    { control: 'PosOpProcALRepair', parentControl: 'PosOpProcAL', conditions: ['Yes'] },
    { control: 'PosOpProcALStent', parentControl: 'PosOpProcAL', conditions: ['Yes'] },
    { control: 'PosOpProcALTube', parentControl: 'PosOpProcAL', conditions: ['Yes'] },
    { control: 'ChyloPres', parentControl: 'PostOpInvProc', conditions: ['Yes'] },
    { control: 'PosOpProcChylotho', parentControl: 'ChyloPres', conditions: ['Yes'] },
    { control: 'PosOpProcEmboli', parentControl: 'PosOpProcChylotho', conditions: ['No'] },
    { control: 'PosOpProcDuctSucc', parentControl: 'PosOpProcEmboli', conditions: ['Yes'] },
    { control: 'AirLeak5', parentControl: 'POEvents', conditions: ['Yes'] },
    { control: 'Atelectasis', parentControl: 'POEvents', conditions: ['Yes'] },
    { control: 'CPlEff', parentControl: 'POEvents', conditions: ['Yes'] },
    { control: 'Pneumonia', parentControl: 'POEvents', conditions: ['Yes'] },
    { control: 'ARDS', parentControl: 'POEvents', conditions: ['Yes'] },
    { control: 'RespFail', parentControl: 'POEvents', conditions: ['Yes'] },
    { control: 'Bronchopleural', parentControl: 'POEvents', conditions: ['Yes'] },
    { control: 'PE', parentControl: 'POEvents', conditions: ['Yes'] },
    { control: 'Pneumo', parentControl: 'POEvents', conditions: ['Yes'] },
    { control: 'Vent', parentControl: 'POEvents', conditions: ['Yes'] },
    { control: 'Trach', parentControl: 'POEvents', conditions: ['Yes'] },
    { control: 'OtherPul', parentControl: 'POEvents', conditions: ['Yes'] },
    { control: 'AtrialArryth', parentControl: 'POEvents', conditions: ['Yes'] },
    { control: 'VentArryth', parentControl: 'POEvents', conditions: ['Yes'] },
    { control: 'MI', parentControl: 'POEvents', conditions: ['Yes'] },
    { control: 'DVT', parentControl: 'POEvents', conditions: ['Yes'] },
    { control: 'OtherCV', parentControl: 'POEvents', conditions: ['Yes'] },
    { control: 'Ileus', parentControl: 'POEvents', conditions: ['Yes'] },
    { control: 'AnastoMed', parentControl: 'POEvents', conditions: ['Yes'] },
    { control: 'DilationEsoph', parentControl: 'POEvents', conditions: ['Yes'] },
    { control: 'CondNecSurg', parentControl: 'POEvents', conditions: ['Yes'] },
    { control: 'DelayCondEmp', parentControl: 'POEvents', conditions: ['Yes'] },
    { control: 'CDiff', parentControl: 'POEvents', conditions: ['Yes'] },
    { control: 'OtherGI', parentControl: 'POEvents', conditions: ['Yes'] },
    { control: 'PostopPRBC', parentControl: 'POEvents', conditions: ['Yes'] },
    { control: 'PostopPRBCUnits', parentControl: 'PostopPRBC', conditions: ['Yes'] },
    { control: 'UTI', parentControl: 'POEvents', conditions: ['Yes'] },
    { control: 'UrinRetent', parentControl: 'POEvents', conditions: ['Yes'] },
    { control: 'DischFoley', parentControl: 'POEvents', conditions: ['Yes'] },
    { control: 'Empyema', parentControl: 'POEvents', conditions: ['Yes'] },
    { control: 'SurgSiteInfect', parentControl: 'POEvents', conditions: ['Yes'] },
    { control: 'Sepsis', parentControl: 'POEvents', conditions: ['Yes'] },
    { control: 'OtherInfect', parentControl: 'POEvents', conditions: ['Yes'] },
    { control: 'CentNeuroEvt', parentControl: 'POEvents', conditions: ['Yes'] },
    { control: 'LaryngealNerve', parentControl: 'POEvents', conditions: ['Yes'] },
    { control: 'Delirium', parentControl: 'POEvents', conditions: ['Yes'] },
    { control: 'OtherNeuro', parentControl: 'POEvents', conditions: ['Yes'] },
    { control: 'RenFailRIFLE', parentControl: 'POEvents', conditions: ['Yes'] },
    { control: 'ChyloMed', parentControl: 'POEvents', conditions: ['Yes'] },
    { control: 'OtherSurg', parentControl: 'POEvents', conditions: ['Yes'] },
    { control: 'UnexpectAdmitICU', parentControl: 'POEvents', conditions: ['Yes'] },
  ],
  sectionM: [
    { control: 'DischDt', parentControl: 'StillInHosp', conditions: ['No'] },
    { control: 'MtDCStat', parentControl: 'StillInHosp', conditions: ['No'] },
    { control: 'DisLoctn', parentControl: 'MtDCStat', conditions: ['Alive'] },
    { control: 'CTubeDis', parentControl: 'StillInHosp', conditions: ['No'] },
    { control: 'DischHomeO2', parentControl: 'StillInHosp', conditions: ['No'] },
    { control: 'OnOxygen30DayPOp', parentControl: 'DischHomeO2', conditions: ['Yes'] },
    { control: 'Readm30Dis', parentControl: 'StillInHosp', conditions: ['No'] },
    { control: 'Readm30DisRel', parentControl: 'Readm30Dis', conditions: ['Yes'] },
  ],
  sectionN: [{ control: 'MortDate', parentControl: 'LFUMortStat', conditions: ['Dead'] }],
  sectionO: [],
};
