import { Validators } from '@angular/forms';

// Title

export const Acsd290Form = {
  sectionA: {
    registryId: [null, Validators.required],
    HN: [null, [Validators.required, Validators.minLength(10), Validators.maxLength(10)]],
    AN: [null, [Validators.required, Validators.minLength(11), Validators.maxLength(12)]],
  },
  sectionB: {
    PatLName: [null, Validators.required],
    PatFName: [null, Validators.required],
    PatMName: [null],
    DOB: [null, Validators.required],
    Age: [null, [Validators.required, Validators.min(0), Validators.max(120)]],
    Gender: [null, Validators.required],
    SSN: [null, Validators.required],
    PatAddr: [null],
    PatNation: [null, Validators.required],
    PermAddr: [null, Validators.required],
  },
  sectionC: {
    HospName: [null, Validators.required],
    PayorPrim: [null, Validators.required],
    PayorSecond: [null, Validators.required],
    AdmitDt: [null, Validators.required],
    SurgDt: [null, Validators.required],
    AdmitSrc: [null, Validators.required],
    OthHosCS: [null, Validators.required],
  },
  sectionD: {
    HeightCM: [null, [Validators.required, Validators.min(20), Validators.max(251)]],
    WeightKg: [null, [Validators.required, Validators.min(10), Validators.max(250)]],
    BMI: [null, Validators.required],
    FHCAD: [null, Validators.required],
    Diabetes: [null, Validators.required],
    DiabCtrl: [null, Validators.required],
    Dyslip: [null, Validators.required],
    Dialysis: [null, Validators.required],
    Hypertn: [null, Validators.required],
    InfEndo: [null, Validators.required],
    InfEndTy: [null, Validators.required],
    InfEndCult: [null, Validators.required],
    TobaccoUse: [null, Validators.required],
    ChrLungD: [null, Validators.required],
    ChrLungDType: [null, Validators.required],
    PFT: [null, Validators.required],
    FEV1: [null, [Validators.required, Validators.min(10), Validators.max(200)]],
    DLCO: [null, Validators.required],
    DLCOPred: [null, [Validators.required, Validators.min(10), Validators.max(200)]],
    ABG: [null, Validators.required],
    PCO2: [null, [Validators.required, Validators.min(20), Validators.max(120)]],
    PO2: [null, [Validators.required, Validators.min(40), Validators.max(500)]],
    HmO2: [null, Validators.required],
    BDTx: [null, Validators.required],
    SlpApn: [null, Validators.required],
    Pneumonia: [null, Validators.required],
    IVDrugAb: [null, Validators.required],
    Depression: [null, Validators.required],
    Alcohol: [null, Validators.required],
    LiverDis: [null, Validators.required],
    LiverChildPugh: [null, Validators.required],
    LiverTransList: [null, Validators.required],
    LiverStatusPost: [null, Validators.required],
    ImmSupp: [null, Validators.required],
    MediastRad: [null, Validators.required],
    Cancer: [null, Validators.required],
    PVD: [null, Validators.required],
    ThAoDisease: [null, Validators.required],
    Syncope: [null, Validators.required],
    UnrespStat: [null, Validators.required],
    ChestWallDef: [null, Validators.required],
    CVD: [null, Validators.required],
    CVA: [null, Validators.required],
    CVAWhen: [null, Validators.required],
    CVDTIA: [null, Validators.required],
    CVDCarSten: [null, Validators.required],
    CVDStenRt: [null, Validators.required],
    CVDStenLft: [null, Validators.required],
    CVDPCarSurg: [null, Validators.required],
    WBC: [null, [Validators.min(100), Validators.max(99990)]],
    RFHemoglobin: [null, [Validators.min(1.0), Validators.max(50.0)]],
    Hct: [null, [Validators.min(1.0), Validators.max(99.99)]],
    Platelets: [null, [Validators.min(1000), Validators.max(900000)]],
    CreatLst: [null, [Validators.min(0.1), Validators.max(30.0)]],
    TotAlbumin: [null, [Validators.min(1.0), Validators.max(10.0)]],
    TotBlrbn: [null, [Validators.min(0.1), Validators.max(50.0)]],
    A1cLvl: [null, [Validators.min(1.0), Validators.max(20.0)]],
    HITAnti: [null],
    INR: [null, [Validators.min(0.5), Validators.max(30.0)]],
    MELDScr: [null, [Validators.min(-50), Validators.max(150)]],
    BNP: [null, [Validators.min(5), Validators.max(70000)]],
    FiveMWalkTest: [null],
    FiveMWalk1: [null, [Validators.min(1), Validators.max(100)]],
    FiveMWalk2: [null, [Validators.min(1), Validators.max(100)]],
    FiveMWalk3: [null, [Validators.min(1), Validators.max(100)]],
    SixMWalkDone: [null],
    SixMWalkDist: [null, [Validators.min(1), Validators.max(3000)]],
  },
  sectionE: {
    PrCVInt: [null, Validators.required],
    PrCAB: [null, Validators.required],
    PrValve: [null, Validators.required],
    PrValveProc1: [null, Validators.required],
    PrValveProc2: [null, Validators.required],
    PrValveProc3: [null, Validators.required],
    PrValveProc4: [null, Validators.required],
    PrValveProc5: [null, Validators.required],
    POCPCI: [null, Validators.required],
    POCPCIWhen: [null, Validators.required],
    POCPCIndSurg: [null, Validators.required],
    POCPCISt: [null, Validators.required],
    POCPCIStTy: [null, Validators.required],
    POCPCIIn: [null, Validators.required],
    POC: [null, Validators.required],
    POCInt1: [null, Validators.required],
    POCInt2: [null, Validators.required],
    POCInt3: [null, Validators.required],
    POCInt4: [null, Validators.required],
    POCInt5: [null, Validators.required],
    POCInt6: [null, Validators.required],
    POCInt7: [null, Validators.required],
  },
  sectionF: {
    PrevMI: [null, Validators.required],
    MIWhen: [null, Validators.required],
    CardSympTimeOfAdm: [null, Validators.required],
    CardSympTimeOfSurg: [null, Validators.required],
    HeartFail: [null, Validators.required],
    HeartFailTmg: [null, Validators.required],
    HeartFailType: [null, Validators.required],
    ClassNYH: [null, Validators.required],
    CarShock: [null, Validators.required],
    Resusc: [null, Validators.required],
    Arrhythmia: [null, Validators.required],
    ArrhythPPaced: [null, Validators.required],
    ArrhythVV: [null, Validators.required],
    ArrhythSSS: [null, Validators.required],
    ArrhythAFlutter: [null, Validators.required],
    ArrhythAFib: [null, Validators.required],
    ArrhythAtrFib: [null, Validators.required],
    ArrhythSecond: [null, Validators.required],
    ArrhythThird: [null, Validators.required],
  },
  sectionG: {
    MedACEI48: [null, Validators.required],
    MedAmiodarone: [null, Validators.required],
    MedBeta: [null, Validators.required],
    MedBetaTher: [null, Validators.required],
    MedCChanTher: [null, Validators.required],
    MedLongActNit: [null, Validators.required],
    MedNitIV: [null, Validators.required],
    MedOthAntiang: [null, Validators.required],
    MedADP5Days: [null, Validators.required],
    MedADPIDis: [null, Validators.required],
    MedASA: [null, Validators.required],
    MedASADis: [null, Validators.required],
    MedASAOnce: [null, Validators.required],
    MedGP: [null, Validators.required],
    MedACoag: [null, Validators.required],
    MedACMN: [null, Validators.required],
    MedCoum5Days: [null, Validators.required],
    MedCoum5Dis: [null, Validators.required],
    MedXa5Days: [null, Validators.required],
    MedXa5DDis: [null, Validators.required],
    MedNOAC5Days: [null, Validators.required],
    MedNOACDisc: [null, Validators.required],
    MedThromIn5Days: [null, Validators.required],
    MedThromInDisc: [null, Validators.required],
    MedThrom: [null, Validators.required],
    MedInotr: [null, Validators.required],
    MedLipid: [null, Validators.required],
    MedLipType: [null, Validators.required],
    MedSter: [null, Validators.required],
  },
  sectionH: {
    CarCathPer: [null, Validators.required],
    CarCathDt: [null, Validators.required],
    CorAnatDisKnown: [null, Validators.required],
    Dominance: [null, Validators.required],
    StenSource: [null, Validators.required],
    NumDisV: [null, Validators.required],
    PctStenKnown: [null, Validators.required],
    GraftsPrsnt: [null, Validators.required],
    StentPrsnt: [null, Validators.required],
    FFRPerf: [null, Validators.required],
    IFRPerf: [null, Validators.required],

    // cath finding
    PctStenLMain: [null, [Validators.min(0), Validators.max(100)]],
    GrftStenLMain: [null],
    StntStenLMain: [null],
    FFRLMain: [null, [Validators.min(0.0), Validators.max(1.0)]],
    IFRLMain: [null, [Validators.min(0.0), Validators.max(1.0)]],

    PctStenProxLAD: [null, [Validators.min(0), Validators.max(100)]],
    GrftStenProxLAD: [null],
    StntStenProxLAD: [null],
    FFRProxLAD: [null, [Validators.min(0.0), Validators.max(1.0)]],
    IFRProxLAD: [null, [Validators.min(0.0), Validators.max(1.0)]],

    PctStenMidLAD: [null, [Validators.min(0), Validators.max(100)]],
    GrftStenMidLAD: [null],
    StntStenMidLAD: [null],
    FFRMidLAD: [null, [Validators.min(0.0), Validators.max(1.0)]],
    IFRMidLAD: [null, [Validators.min(0.0), Validators.max(1.0)]],

    PctStenDistLAD: [null, [Validators.min(0), Validators.max(100)]],
    GrftStenDistLAD: [null],
    StntStenDistLAD: [null],
    FFRDistLAD: [null, [Validators.min(0.0), Validators.max(1.0)]],
    IFRDistLAD: [null, [Validators.min(0.0), Validators.max(1.0)]],

    PctStenDiag1: [null, [Validators.min(0), Validators.max(100)]],
    GrftStenDiag1: [null],
    StntStenDiag1: [null],
    FFRDiag1: [null, [Validators.min(0.0), Validators.max(1.0)]],
    IFRDiag1: [null, [Validators.min(0.0), Validators.max(1.0)]],

    PctStenDiag2: [null, [Validators.min(0), Validators.max(100)]],
    GrftStenDiag2: [null],
    StntStenDiag2: [null],
    FFRDiag2: [null, [Validators.min(0.0), Validators.max(1.0)]],
    IFRDiag2: [null, [Validators.min(0.0), Validators.max(1.0)]],

    PctStenDiag3: [null, [Validators.min(0), Validators.max(100)]],
    GrftStenDiag3: [null],
    StntStenDiag3: [null],
    FFRDiag3: [null, [Validators.min(0.0), Validators.max(1.0)]],
    IFRDiag3: [null, [Validators.min(0.0), Validators.max(1.0)]],

    PctStenCircflx: [null, [Validators.min(0), Validators.max(100)]],
    GrftStenCircflx: [null],
    StntStenCircflx: [null],
    FFRCircflx: [null, [Validators.min(0.0), Validators.max(1.0)]],
    IFRCircflx: [null, [Validators.min(0.0), Validators.max(1.0)]],

    PctStenOM1: [null, [Validators.min(0), Validators.max(100)]],
    GrftStenOM1: [null],
    StntStenOM1: [null],
    FFROM1: [null, [Validators.min(0.0), Validators.max(1.0)]],
    IFROM1: [null, [Validators.min(0.0), Validators.max(1.0)]],

    PctStenOM2: [null, [Validators.min(0), Validators.max(100)]],
    GrftStenOM2: [null],
    StntStenOM2: [null],
    FFROM2: [null, [Validators.min(0.0), Validators.max(1.0)]],
    IFROM2: [null, [Validators.min(0.0), Validators.max(1.0)]],

    PctStenOM3: [null, [Validators.min(0), Validators.max(100)]],
    GrftStenOM3: [null],
    StntStenOM3: [null],
    FFROM3: [null, [Validators.min(0.0), Validators.max(1.0)]],
    IFROM3: [null, [Validators.min(0.0), Validators.max(1.0)]],

    PctStenRamus: [null, [Validators.min(0), Validators.max(100)]],
    GrftStenRamus: [null],
    StntStenRamus: [null],
    FFRRamus: [null, [Validators.min(0.0), Validators.max(1.0)]],
    IFRRamus: [null, [Validators.min(0.0), Validators.max(1.0)]],

    PctStenRCA: [null, [Validators.min(0), Validators.max(100)]],
    GrftStenRCA: [null],
    StntStenRCA: [null],
    FFRRCA: [null, [Validators.min(0.0), Validators.max(1.0)]],
    IFRRCA: [null, [Validators.min(0.0), Validators.max(1.0)]],

    PctStenAM: [null, [Validators.min(0), Validators.max(100)]],
    GrftStenAM: [null],
    StntStenAM: [null],
    FFRAM: [null, [Validators.min(0.0), Validators.max(1.0)]],
    IFRAM: [null, [Validators.min(0.0), Validators.max(1.0)]],

    PctStenPDA: [null, [Validators.min(0), Validators.max(100)]],
    GrftStenPDA: [null],
    StntStenPDA: [null],
    FFRPDA: [null, [Validators.min(0.0), Validators.max(1.0)]],
    IFRPDA: [null, [Validators.min(0.0), Validators.max(1.0)]],

    PctStenPLB: [null, [Validators.min(0), Validators.max(100)]],
    GrftStenPLB: [null],
    StntStenPLB: [null],
    FFRPLB: [null, [Validators.min(0.0), Validators.max(1.0)]],
    IFRPLB: [null, [Validators.min(0.0), Validators.max(1.0)]],

    SyntaxScrKnown: [null, Validators.required],
    SyntaxScr: [null, [Validators.required, Validators.min(0), Validators.max(100)]],
    StressTst: [null, Validators.required],
    StrsTstRes: [null, Validators.required],
    HDEFD: [null, Validators.required],
    HDEF: [null, [Validators.required, Validators.min(1), Validators.max(99)]],
    DimAvail: [null, Validators.required],
    LVSD: [null, [Validators.required, Validators.min(0.0), Validators.max(99.0)]],
    LVEDD: [null, [Validators.required, Validators.min(20.0), Validators.max(100.0)]],
    PASYSMeas: [null, Validators.required],
    PASYS: [null, [Validators.required, Validators.min(10), Validators.max(150)]],

    VDInsufA: [null, Validators.required],
    VDAVEccJet: [null, Validators.required],
    VDAort: [null, Validators.required],
    VDStenA: [null, Validators.required],
    AoHemoDatAvail: [null, Validators.required],
    VDAoVA: [null, [Validators.required, Validators.min(0.2), Validators.max(5.0)]],
    VDGradA: [null, [Validators.required, Validators.min(0), Validators.max(200)]],
    VDVMax: [null, [Validators.required, Validators.min(0), Validators.max(8)]],
    VDAoPrimEt: [null, Validators.required],
    VDAoSievers: [null, Validators.required],

    VDInsufM: [null, Validators.required],
    VDMVEccJet: [null, Validators.required],
    VDMit: [null, Validators.required],
    VDStenM: [null, Validators.required],
    MiHemoDatAvail: [null, Validators.required],
    VDMVA: [null, [Validators.required, Validators.min(0.6), Validators.max(6.0)]],
    VDGradM: [null, [Validators.required, Validators.min(0), Validators.max(30)]],
    VDMiPrimEt: [null, Validators.required],
    VDMiPrimLes: [null, Validators.required],

    VDInsufT: [null, Validators.required],
    VDTrAnnMeas: [null, Validators.required],
    VDTrAnnSize: [null, [Validators.required, Validators.min(1.5), Validators.max(10.0)]],
    VDTr: [null, Validators.required],
    VDStenT: [null, Validators.required],
    VDTrPrimEt: [null, Validators.required],

    VDInsufP: [null, Validators.required],
    VDPulm: [null, Validators.required],
    RVEDDKnown: [null, Validators.required],
    RVEDD: [null, [Validators.required, Validators.min(0.5), Validators.max(5.0)]],
    VDStenP: [null, Validators.required],
    PuHemoDatAvail: [null, Validators.required],
    VDGradP: [null, [Validators.required, Validators.min(0), Validators.max(200)]],
    VDPuEt: [null, Validators.required],
  },
  sectionI: {
    Procedure1: [null, Validators.required],
    Procedure2: [null],
    Procedure3: [null],
    Procedure4: [null],
    SurgeonId: [null, Validators.required],
    Assist1Id: [null],
    Assist2Id: [null],
    Assist3Id: [null],
    Assist4Id: [null],
    Assist5Id: [null],
    Assist6Id: [null],
    Anesth1Id: [null, Validators.required],
    Anesth2Id: [null],
    Scrub1Id: [null, Validators.required],
    Scrub2Id: [null],
    Scrub3Id: [null],
    Scrub4Id: [null],
    CTT1Id: [null, Validators.required],
    CTT2Id: [null],
    CTT3Id: [null],
    CTT4Id: [null],

    RiskDiscussed: [null, Validators.required],
    STSscore: [null, Validators.required],
    EUROscore: [null, Validators.required],
    Incidenc: [null, Validators.required],
    Status: [null, Validators.required],
    UrgEmergRsn: [null, Validators.required],

    PCancCase: [null, Validators.required],
    PCancCaseDt: [null, Validators.required],
    PCancCaseTmg: [null, Validators.required],
    PCancCaseRsn: [null, Validators.required],
    PCancCaseCAB: [null, Validators.required],
    PCancCaseMech: [null, Validators.required],
    PCancCaseONC: [null, Validators.required],
    PCancCaseValSur: [null, Validators.required],
    PCancCaseValTrans: [null, Validators.required],
    PCancCaseOC: [null, Validators.required],

    CCancCase: [null, Validators.required],
    CCancCaseTmg: [null, Validators.required],
    CCancCaseRsn: [null, Validators.required],
    CCancCaseCAB: [null, Validators.required],
    CCancCaseMech: [null, Validators.required],
    CCancCaseONC: [null, Validators.required],
    CCancCaseValSur: [null, Validators.required],
    CCancCaseValTrans: [null, Validators.required],
    CCancCaseOC: [null, Validators.required],

    OPApp: [null, Validators.required],
    ApproachCon: [null, Validators.required],
    Robotic: [null, Validators.required],
    RobotTim: [null, Validators.required],

    OpCAB: [null, Validators.required],
    OpValve: [null, Validators.required],
    OpValSurgInput: [null, Validators.required],
    AortProc: [null, Validators.required],
    AortProcSurgInput: [null, Validators.required],
    OpOCard: [null, Validators.required],
    AFibProc: [null, Validators.required],
    AFibProcSurgInput: [null, Validators.required],
    OpONCard: [null, Validators.required],

    OREntryDT: [null, Validators.required],
    ORExitDT: [null, Validators.required],
    GenAnes: [null, Validators.required],
    ProcSed: [null, Validators.required],
    Intubate: [null, Validators.required],
    IntubateDT: [null, Validators.required],
    ExtubateDT: [null, Validators.required],
    SIStartDT: [null, Validators.required],
    SIStopDT: [null, Validators.required],
    AnesEndDT: [null, Validators.required],
    AbxSelect: [null, Validators.required],
    AbxTiming: [null, Validators.required],
    AbxDisc: [null, Validators.required],
    AddIntraopPAnti: [null, Validators.required],
    TempMeas: [null, Validators.required],
    LwstTemp: [null, [Validators.required, Validators.min(5.0), Validators.max(40.0)]],
    LwstTempSrc: [null, Validators.required],
    LwstIntraHemo: [null, [Validators.required, Validators.min(1.0), Validators.max(50.0)]],
    LwstHct: [null, [Validators.required, Validators.min(1.0), Validators.max(99.99)]],
    HighIntraGlu: [null, [Validators.required, Validators.min(40), Validators.max(2000)]],

    CPBUtil: [null, Validators.required],
    CPBCmb: [null, Validators.required],
    CPBCmbR: [null, Validators.required],

    CanArtStAort: [null, Validators.required],
    CanArtStFem: [null, Validators.required],
    CanArtStAx: [null, Validators.required],
    CanArtStInn: [null, Validators.required],
    CanArtStOth: [null, Validators.required],

    CanVenStFem: [null, Validators.required],
    CanVenStJug: [null, Validators.required],
    CanVenStRtA: [null, Validators.required],
    CanVenStLfA: [null, Validators.required],
    CanVenStPulm: [null, Validators.required],
    CanVenStBi: [null, Validators.required],
    CanVenStOth: [null, Validators.required],

    PerfusTm: [null, Validators.required],
    CircArr: [null, Validators.required],
    DHCATm: [null, [Validators.required, Validators.min(0), Validators.max(300)]],
    CPerfUtil: [null, Validators.required],
    CPerfTime: [null, [Validators.required, Validators.min(1), Validators.max(999)]],
    CPerfTyp: [null, Validators.required],
    TotCircArrTm: [null, Validators.required],

    AortOccl: [null, Validators.required],
    XClampTm: [null, [Validators.required, Validators.min(0), Validators.max(600)]],
    CplegiaDeliv: [null, Validators.required],
    CplegiaType: [null, Validators.required],
    CerOxUsed: [null, Validators.required],
    ConCalc: [null, Validators.required],
    AsmtAscAA: [null, Validators.required],
    AsmtAoDxMeth: [null, Validators.required],
    AsmtAoDx: [null, Validators.required],
    AsmtAPln: [null, Validators.required],

    IBldProdRef: [null, Validators.required],
    IBldProd: [null, Validators.required],
    IBdRBCU: [null, [Validators.required, Validators.min(0), Validators.max(99)]],
    IBdFFPU: [null, [Validators.required, Validators.min(0), Validators.max(99)]],
    IBdPlatU: [null, [Validators.required, Validators.min(0), Validators.max(99)]],
    IBdCryoU: [null, [Validators.required, Validators.min(0), Validators.max(99)]],

    IntraClotFact: [null, Validators.required],
    IntraopProComCon: [null, Validators.required],
    IMedEACA: [null, Validators.required],
    IMedTran: [null, Validators.required],

    InOpTEE: [null, Validators.required],
    PRepAR: [null, Validators.required],
    PRepAGradM: [null, [Validators.required, Validators.min(0), Validators.max(200)]],
    PRepAPVL: [null, Validators.required],
    PRepMR: [null, Validators.required],
    PRepMGradM: [null, [Validators.required, Validators.min(0), Validators.max(30)]],
    PRepMPVL: [null, Validators.required],
    PRepTR: [null, Validators.required],
    PRepTGradM: [null, [Validators.required, Validators.min(0), Validators.max(100)]],
    PRepTPVL: [null, Validators.required],
    PPEFMeas: [null, Validators.required],
    PPEF: [null, [Validators.required, Validators.min(1.0), Validators.max(99.0)]],
    PPPlanedPCI: [null, Validators.required],
  },
  sectionJ: {
    IMAUsed: [null, Validators.required],
    NoIMARsn: [null, Validators.required],
    NumIMADA: [null, [Validators.required, Validators.min(0), Validators.max(6)]],
    LeftIMA: [null, Validators.required],
    LIMAHarvTech: [null, Validators.required],
    RightIMA: [null, Validators.required],
    RIMAHarvTech: [null, Validators.required],
    RadialArtUsed: [null, Validators.required],
    NumRadDA: [null, [Validators.required, Validators.min(0), Validators.max(6)]],
    RadHTech: [null, Validators.required],
    RadHarvPrepTm: [null, [Validators.min(0), Validators.max(240)]],
    VenousCondUsed: [null, Validators.required],
    DistVein: [null, [Validators.required, Validators.min(0), Validators.max(9)]],
    DistVeinHTech: [null, Validators.required],
    SaphHarPrepTm: [null, [Validators.min(0), Validators.max(240)]],
    NumOArtD: [null, [Validators.required, Validators.min(0), Validators.max(6)]],
    NumArtVenComp: [null, [Validators.required, Validators.min(0), Validators.max(5)]],
    NumVenArtComp: [null, [Validators.required, Validators.min(0), Validators.max(5)]],
    NumArtArtComp: [null, [Validators.required, Validators.min(0), Validators.max(5)]],
    ProxTech: [null, Validators.required],

    CAB01: [null, Validators.required],
    CABDistSite01: [null, Validators.required],
    CABProximalSite01: [null, Validators.required],
    CABConduit01: [null, Validators.required],
    CABDistPos01: [null, Validators.required],
    CABEndArt01: [null, Validators.required],
    CABVeinPatAng01: [null, Validators.required],

    CAB02: [null, Validators.required],
    CABDistSite02: [null, Validators.required],
    CABProximalSite02: [null, Validators.required],
    CABConduit02: [null, Validators.required],
    CABDistPos02: [null, Validators.required],
    CABEndArt02: [null, Validators.required],
    CABVeinPatAng02: [null, Validators.required],

    CAB03: [null, Validators.required],
    CABDistSite03: [null, Validators.required],
    CABProximalSite03: [null, Validators.required],
    CABConduit03: [null, Validators.required],
    CABDistPos03: [null, Validators.required],
    CABEndArt03: [null, Validators.required],
    CABVeinPatAng03: [null, Validators.required],

    CAB04: [null, Validators.required],
    CABDistSite04: [null, Validators.required],
    CABProximalSite04: [null, Validators.required],
    CABConduit04: [null, Validators.required],
    CABDistPos04: [null, Validators.required],
    CABEndArt04: [null, Validators.required],
    CABVeinPatAng04: [null, Validators.required],

    CAB05: [null, Validators.required],
    CABDistSite05: [null, Validators.required],
    CABProximalSite05: [null, Validators.required],
    CABConduit05: [null, Validators.required],
    CABDistPos05: [null, Validators.required],
    CABEndArt05: [null, Validators.required],
    CABVeinPatAng05: [null, Validators.required],

    CAB06: [null, Validators.required],
    CABDistSite06: [null, Validators.required],
    CABProximalSite06: [null, Validators.required],
    CABConduit06: [null, Validators.required],
    CABDistPos06: [null, Validators.required],
    CABEndArt06: [null, Validators.required],
    CABVeinPatAng06: [null, Validators.required],

    CAB07: [null, Validators.required],
    CABDistSite07: [null, Validators.required],
    CABProximalSite07: [null, Validators.required],
    CABConduit07: [null, Validators.required],
    CABDistPos07: [null, Validators.required],
    CABEndArt07: [null, Validators.required],
    CABVeinPatAng07: [null, Validators.required],

    CAB08: [null, Validators.required],
    CABDistSite08: [null, Validators.required],
    CABProximalSite08: [null, Validators.required],
    CABConduit08: [null, Validators.required],
    CABDistPos08: [null, Validators.required],
    CABEndArt08: [null, Validators.required],
    CABVeinPatAng08: [null, Validators.required],

    CAB09: [null, Validators.required],
    CABDistSite09: [null, Validators.required],
    CABProximalSite09: [null, Validators.required],
    CABConduit09: [null, Validators.required],
    CABDistPos09: [null, Validators.required],
    CABEndArt09: [null, Validators.required],
    CABVeinPatAng09: [null, Validators.required],

    CAB10: [null, Validators.required],
    CABDistSite10: [null, Validators.required],
    CABProximalSite10: [null, Validators.required],
    CABConduit10: [null, Validators.required],
    CABDistPos10: [null, Validators.required],
    CABEndArt10: [null, Validators.required],
    CABVeinPatAng10: [null, Validators.required],
  },
  sectionK: {
    ValExp: [null, Validators.required],
    ValExpPos: [null, Validators.required],
    ValExpTyp: [null, Validators.required],
    ValExpEt: [null, Validators.required],
    ValExpDevKnown: [null, Validators.required],
    ValExpDev: [null, Validators.required],
    ValExpUDI: [null, Validators.required],
    ValExp2: [null, Validators.required],
    ValExpPos2: [null, Validators.required],
    ValExpTyp2: [null, Validators.required],
    ValExpEt2: [null, Validators.required],
    ValExpDevKnown2: [null, Validators.required],
    ValExpDev2: [null, Validators.required],
    ValExpUDI2: [null, Validators.required],

    //  AORTIC VALVE
    VSAV: [null, Validators.required],
    VSAVPr: [null, Validators.required],
    VSTCV: [null, Validators.required],
    VSTCVR: [null, Validators.required],
    VSAVSurgRep: [null, Validators.required],
    VSAVSurgType: [null, Validators.required],
    VSAVSurgBioT: [null, Validators.required],

    VSAVRComA: [null, Validators.required],
    VSAVRExSutAn: [null, Validators.required],
    VSAVRLPlic: [null, Validators.required],
    VSAVRNodRel: [null, Validators.required],
    VSAVRPTFE: [null, Validators.required],
    VSAVRComRS: [null, Validators.required],
    VSAVRRaphe: [null, Validators.required],
    VSAVRRingA: [null, Validators.required],
    VSAVRRingATy: [null, Validators.required],
    VSAVRLResect: [null, Validators.required],
    VSAVRLeafShav: [null, Validators.required],
    VSAVRLPPatch: [null, Validators.required],
    VSAVRDeb: [null, Validators.required],
    VSAVRPeriLeak: [null, Validators.required],
    AnlrEnl: [null, Validators.required],
    AnlrEnlTech: [null, Validators.required],
    VSAVRoot: [null, Validators.required],
    VSAVRootOReimp: [null, Validators.required],
    VSAVRootOReimpTy: [null, Validators.required],
    VSAVRepBioTy: [null, Validators.required],
    VSAVSparRt: [null, Validators.required],
    VSAVSparRtOp: [null, Validators.required],
    VSAVRootRecon: [null, Validators.required],
    VSAVPat: [null, Validators.required],
    VSAVPatTy: [null, Validators.required],
    AorticImplant: [null, Validators.required],
    VSAoIm: [null, Validators.required],
    VSAoImSz: [null, [Validators.required, Validators.min(5), Validators.max(100)]],
    VSAoImUDI: [null, Validators.required],

    //  MITRAL VALVE
    VSMV: [null, Validators.required],
    VSMVPr: [null, Validators.required],
    VSMVRepApp: [null, Validators.required],
    VSMitRAnnulo: [null, Validators.required],

    //  LEAFLET RESECTION
    VSMitRLeafRes: [null, Validators.required],
    VSLeafResTyp: [null, Validators.required],
    VSLeafAntRes: [null, Validators.required],
    VSLeafAntResLocD: [null, Validators.required],
    VSLeafAntResA1: [null, Validators.required],
    VSLeafAntResA2: [null, Validators.required],
    VSLeafAntResA3: [null, Validators.required],
    VSLeafPostRes: [null, Validators.required],
    VSLeafPostResLocD: [null, Validators.required],
    VSLeafPostResP1: [null, Validators.required],
    VSLeafPostResP2: [null, Validators.required],
    VSLeafPostResP3: [null, Validators.required],
    VSLeafComRes: [null, Validators.required],
    VSLeafComResLoc: [null, Validators.required],

    //  NEOCORDS (PTFE)
    VSMitRPTFE: [null, Validators.required],
    VSNeoAnt: [null, Validators.required],
    VSNeoAntLocD: [null, Validators.required],
    VSNeoAntA1: [null, Validators.required],
    VSNeoAntA2: [null, Validators.required],
    VSNeoAntA3: [null, Validators.required],
    VSNeoPost: [null, Validators.required],
    VSNeoPostLocD: [null, Validators.required],
    VSNeoPostP1: [null, Validators.required],
    VSNeoPostP2: [null, Validators.required],
    VSNeoPostP3: [null, Validators.required],
    VSNeoCom: [null, Validators.required],
    VSNeoComLoc: [null, Validators.required],

    //  NEOCORDS (PTFE)
    VSMitRChord: [null, Validators.required],
    VSChorLfAnt: [null, Validators.required],
    VSChorLfAntLocD: [null, Validators.required],
    VSChorLfAntA1: [null, Validators.required],
    VSChorLfAntA2: [null, Validators.required],
    VSChorLfAntA3: [null, Validators.required],
    VSChorLfPost: [null, Validators.required],
    VSChorLfPostLocD: [null, Validators.required],
    VSChorLfPostP1: [null, Validators.required],
    VSChorLfPostP2: [null, Validators.required],
    VSChorLfPostP3: [null, Validators.required],
    VSChorLfCom: [null, Validators.required],
    VSChorLfComLoc: [null, Validators.required],

    VSMitRFold: [null, Validators.required],
    VSMitRSlidP: [null, Validators.required],
    VSMitRADecalc: [null, Validators.required],
    VSMitRLeafERP: [null, Validators.required],
    VSMitRLeafERPLoc: [null, Validators.required],
    VSMitREdge: [null, Validators.required],
    VSMitRMitComm: [null, Validators.required],
    VSMitRMitCplasty: [null, Validators.required],
    VSMitRMitCleft: [null, Validators.required],
    VSMitParaprosLeak: [null, Validators.required],

    MitralIntent: [null, Validators.required],
    VSChorPres: [null, Validators.required],
    VSTCVMit: [null, Validators.required],

    MitralImplant: [null, Validators.required],
    MitralImplantTy: [null, Validators.required],
    VSMiIm: [null, Validators.required],
    VSMiImSz: [null, [Validators.required, Validators.min(5), Validators.max(100)]],
    VSMiImUDI: [null, Validators.required],

    //  TRICUSPID VALVE
    VSTV: [null, Validators.required],
    VSTVPr: [null, Validators.required],
    VSTrRepAnnulo: [null, Validators.required],
    OpTricusAnTy: [null, Validators.required],
    VSTrLeafRes: [null, Validators.required],
    VSTCVTri: [null, Validators.required],
    TricuspidImplant: [null, Validators.required],
    TricusImplantTy: [null, Validators.required],
    VSTrIm: [null, Validators.required],
    VSTrImSz: [null, [Validators.required, Validators.min(5), Validators.max(100)]],
    VSTrImUDI: [null, Validators.required],

    //  PULMONIC VALVE
    VSPV: [null, Validators.required],
    OpPulm: [null, Validators.required],
    VSTCVPu: [null, Validators.required],
    PulmonicImplant: [null, Validators.required],
    VSPuTypeImp: [null, Validators.required],
    VSPuImpMat: [null, Validators.required],
    PulmonicImplantTy: [null, Validators.required],
    VSPuIm: [null, Validators.required],
    VSPuImSz: [null, [Validators.required, Validators.min(5), Validators.max(100)]],
    VSPuImUDI: [null, Validators.required],
  },
  sectionL: {
    IABP: [null, Validators.required],
    IABPWhen: [null, Validators.required],
    IABPInd: [null, Validators.required],
    CathBasAssist: [null, Validators.required],
    CathBasAssistTy: [null, Validators.required],
    CathBasAssistWhen: [null, Validators.required],
    CathBasAssistInd: [null, Validators.required],
    ECMO: [null, Validators.required],
    ECMOWhen: [null, Validators.required],
    ECMOInd: [null, Validators.required],
  },
  sectionL2: {
    PrevVAD: [null, Validators.required],
    PrevVADF: [null, Validators.required],
    PrevVADD: [null, Validators.required],
    PrevVADIn: [null, Validators.required],
    PrevVADTy: [null, Validators.required],
    PrevVADDevice: [null, Validators.required],
    PrevVADUDI: [null, Validators.required],
    PrevVADExp: [null, Validators.required],
    PrevVADExpRsn: [null, Validators.required],
    PrevVADExpDt: [null, Validators.required],

    VADImp: [null, Validators.required],
    VImp: [null, Validators.required],
    VADImpTmg: [null, Validators.required],
    VImpDt: [null, Validators.required],
    VADInd: [null, Validators.required],
    VImpTy: [null, Validators.required],
    VProdTy: [null, Validators.required],
    VImpUDI: [null, Validators.required],
    VExp: [null, Validators.required],
    VExpRsn: [null, Validators.required],
    VExpDt: [null, Validators.required],

    VImp2: [null, Validators.required],
    VADImpTmg2: [null, Validators.required],
    VImpDt2: [null, Validators.required],
    VADInd2: [null, Validators.required],
    VImpTy2: [null, Validators.required],
    VProdTy2: [null, Validators.required],
    VImpUDI2: [null, Validators.required],
    VExp2: [null, Validators.required],
    VExpRsn2: [null, Validators.required],
    VExpDt2: [null, Validators.required],

    VImp3: [null, Validators.required],
    VADImpTmg3: [null, Validators.required],
    VImpDt3: [null, Validators.required],
    VADInd3: [null, Validators.required],
    VImpTy3: [null, Validators.required],
    VProdTy3: [null, Validators.required],
    VImpUDI3: [null, Validators.required],
    VExp3: [null, Validators.required],
    VExpRsn3: [null, Validators.required],
    VExpDt3: [null, Validators.required],
  },
  sectionM: {
    OCarASDPFO: [null, Validators.required],
    OCarASDSec: [null, Validators.required],
    OCarAFibIntraLes: [null, Validators.required],
    OCarAFibEpLes: [null, Validators.required],
    OCarAAProc: [null, Validators.required],
    OCarAAMeth: [null, Validators.required],
    OCarAAModel: [null, Validators.required],
    OCarAAUDI: [null, Validators.required],
    OCarACD: [null, Validators.required],
    OCarLeadInsert: [null, Validators.required],
    OCarACDLE: [null, Validators.required],
    OCarCong: [null, Validators.required],
    OCarLVA: [null, Validators.required],
    OCarStemCell: [null, Validators.required],
    OCPulThromDis: [null, Validators.required],
    OCarSubaStenRes: [null, Validators.required],
    OCarSubaStenResTy: [null, Validators.required],
    OCarSVR: [null, Validators.required],
    OCarLasr: [null, Validators.required],
    OCTumor: [null, Validators.required],
    OCarCrTx: [null, Validators.required],
    OCarTrma: [null, Validators.required],
    OCarVSD: [null, Validators.required],
    OCarOthr: [null, Validators.required],
  },
  sectionM1: {
    OCarAFibLesLoc: [null, Validators.required],
    OCarAFibMethRad: [null, Validators.required],
    OCarAFibMethRadBi: [null, Validators.required],
    OCarAFibMethCAS: [null, Validators.required],
    OCarAFibMethCryo: [null, Validators.required],
    OCarLesDoc: [null, Validators.required],
    AFibLes1: [null, Validators.required],
    AFibLes2: [null, Validators.required],
    AFibLes3a: [null, Validators.required],
    AFibLes3b: [null, Validators.required],
    AFibLes4: [null, Validators.required],
    AFibLes5: [null, Validators.required],
    AFibLes6: [null, Validators.required],
    AFibLes7: [null, Validators.required],
    AFibLes8: [null, Validators.required],
    AFibLes9: [null, Validators.required],
    AFibLes10: [null, Validators.required],
    AFibLes11: [null, Validators.required],
    AFibLes12: [null, Validators.required],
    AFibLes13: [null, Validators.required],
    AFibLes14: [null, Validators.required],
    AFibLes15a: [null, Validators.required],
    AFibLes15b: [null, Validators.required],
    AFitLesCSL: [null, Validators.required],
  },
  sectionM2: {
    FamHistAorta: [null, Validators.required],
    PatGenHist: [null, Validators.required],
    PriorAorta: [null, Validators.required],

    PriorRepRoot: [null, Validators.required],
    PriorRepTyRoot: [null, Validators.required],
    PriorFailRoot: [null, Validators.required],
    PriorProgRoot: [null, Validators.required],

    PriorRepAsc: [null, Validators.required],
    PriorRepTyAsc: [null, Validators.required],
    PriorFailAsc: [null, Validators.required],
    PriorProgAsc: [null, Validators.required],

    PriorRepArch: [null, Validators.required],
    PriorRepTyArch: [null, Validators.required],
    PriorFailArch: [null, Validators.required],
    PriorProgArch: [null, Validators.required],

    PriorRepDesc: [null, Validators.required],
    PriorRepTyDesc: [null, Validators.required],
    PriorFailDesc: [null, Validators.required],
    PriorProgDesc: [null, Validators.required],

    PriorRepSupraAb: [null, Validators.required],
    PriorRepTySupraAb: [null, Validators.required],
    PriorFailSupraAb: [null, Validators.required],
    PriorProgSupraAb: [null, Validators.required],

    PriorRepInfraAb: [null, Validators.required],
    PriorRepTyInfraAb: [null, Validators.required],
    PriorFailInfraAb: [null, Validators.required],
    PriorProgInfraAb: [null, Validators.required],

    Endoleak: [null, Validators.required],
    EndoleakTypeI: [null, Validators.required],
    EndoleakTyILoc: [null, Validators.required],
    EndoleakTypeII: [null, Validators.required],
    EndoleakVessNum: [null, Validators.required],
    EndoleakTypeIII: [null, Validators.required],
    EndoleakType: [null, Validators.required],
    EndoleakTypeIV: [null, Validators.required],
    EndoleakTypeV: [null, Validators.required],

    Infection: [null, Validators.required],
    InfecType: [null, Validators.required],

    Trauma: [null, Validators.required],
    TraumacRoot: [null, Validators.required],
    TraumaAsc: [null, Validators.required],
    TraumaArch: [null, Validators.required],
    TraumaDesc: [null, Validators.required],
    TraumaThorac: [null, Validators.required],
    TraumaAbdom: [null, Validators.required],

    Presentation: [null, Validators.required],
    PrimIndic: [null, Validators.required],

    //  ANEURYSM
    AnEtilogy: [null, Validators.required],
    AnType: [null, Validators.required],
    AnRupt: [null, Validators.required],
    AnRuptCon: [null, Validators.required],
    AnLoc: [null, Validators.required],

    //  DISSECTION
    DisTiming: [null, Validators.required],
    DisOnsetDtKnown: [null, Validators.required],
    DisOnsetDt: [null, Validators.required],
    DisTearLoc: [null, Validators.required],
    DisSecLoc: [null, Validators.required],
    DisRetExt: [null, Validators.required],
    DisRetLoc: [null, Validators.required],
    DisPosTEVAR: [null, Validators.required],
    DistalExt: [null, Validators.required],
    DistalExtLoc: [null, Validators.required],

    DisMal: [null, Validators.required],
    DisMalCor: [null, Validators.required],
    DisMalRtSubclav: [null, Validators.required],
    DisMalRtComCar: [null, Validators.required],
    DisMalComL: [null, Validators.required],
    DisMalSubL: [null, Validators.required],
    DisMalCel: [null, Validators.required],
    DisMalSup: [null, Validators.required],
    DisMalRenL: [null, Validators.required],
    DisMalRenR: [null, Validators.required],
    DisMalIlio: [null, Validators.required],
    DisMalSpin: [null, Validators.required],

    DisLowMotFun: [null, Validators.required],
    DisLowSenDef: [null, Validators.required],
    DisRupt: [null, Validators.required],
    DisRuptCon: [null, Validators.required],
    DisRuptLoc: [null, Validators.required],

    //  ROOT
    RootAAnnEctasia: [null, Validators.required],
    RootDilaAsym: [null, Validators.required],
    RoottDilaAsym: [null, Validators.required],
    RootSinus: [null, Validators.required],
    RootSinusLoc: [null, Validators.required],

    //  ARCH
    ArchType: [null, Validators.required],
    ArchAbRtSub: [null, Validators.required],
    ArchAbLtSub: [null, Validators.required],
    ArchKom: [null, Validators.required],
    ArchBovine: [null, Validators.required],
    ArchVarVertOr: [null, Validators.required],
    ArchPatIMA: [null, Validators.required],

    //  ASCENDING
    AscAsymDil: [null, Validators.required],
    AscProxGr: [null, Validators.required],

    //  3-D RECONSCTRUCTION
    Diameter3DMeas: [null, Validators.required],
    Diam3DAnnulus: [null, [Validators.required, Validators.min(10), Validators.max(120)]],
    Diam3DSinus: [null, [Validators.required, Validators.min(10), Validators.max(120)]],
    Diam3DSinotubular: [null, [Validators.required, Validators.min(10), Validators.max(120)]],
    Diam3DMidAsc: [null, [Validators.required, Validators.min(10), Validators.max(120)]],
    Diam3DDistalAsc: [null, [Validators.required, Validators.min(10), Validators.max(120)]],
    Diam3DZone1: [null, [Validators.required, Validators.min(10), Validators.max(120)]],
    Diam3DZone2: [null, [Validators.required, Validators.min(10), Validators.max(120)]],
    Diam3DZone3: [null, [Validators.required, Validators.min(10), Validators.max(120)]],
    Diam3DZone4: [null, [Validators.required, Validators.min(10), Validators.max(120)]],
    Diam3DZone5: [null, [Validators.required, Validators.min(10), Validators.max(120)]],
    Diam3DZone6: [null, [Validators.required, Validators.min(10), Validators.max(120)]],
    Diam3DZone7: [null, [Validators.required, Validators.min(10), Validators.max(120)]],
    Diam3DZone8: [null, [Validators.required, Validators.min(10), Validators.max(120)]],
    Diam3DZone9: [null, [Validators.required, Validators.min(10), Validators.max(120)]],
    Diam3DZone10: [null, [Validators.required, Validators.min(10), Validators.max(120)]],
    Diam3DZone11: [null, [Validators.required, Validators.min(10), Validators.max(120)]],

    //  LARGEST PREOP DIAMETER
    DiamLgstAnnulus: [null, [Validators.required, Validators.min(10), Validators.max(120)]],
    DiamLgstSinus: [null, [Validators.required, Validators.min(10), Validators.max(120)]],
    DiamLgstSinotubular: [null, [Validators.required, Validators.min(10), Validators.max(120)]],
    DiamLgstMidAsc: [null, [Validators.required, Validators.min(10), Validators.max(120)]],
    DiamLgstDistalAsc: [null, [Validators.required, Validators.min(10), Validators.max(120)]],
    DiamLgstZone1: [null, [Validators.required, Validators.min(10), Validators.max(120)]],
    DiamLgstZone2: [null, [Validators.required, Validators.min(10), Validators.max(120)]],
    DiamLgstZone3: [null, [Validators.required, Validators.min(10), Validators.max(120)]],
    DiamLgstZone4: [null, [Validators.required, Validators.min(10), Validators.max(120)]],
    DiamLgstZone5: [null, [Validators.required, Validators.min(10), Validators.max(120)]],
    DiamLgstZone6: [null, [Validators.required, Validators.min(10), Validators.max(120)]],
    DiamLgstZone7: [null, [Validators.required, Validators.min(10), Validators.max(120)]],
    DiamLgstZone8: [null, [Validators.required, Validators.min(10), Validators.max(120)]],
    DiamLgstZone9: [null, [Validators.required, Validators.min(10), Validators.max(120)]],
    DiamLgstZone10: [null, [Validators.required, Validators.min(10), Validators.max(120)]],
    DiamLgstZone11: [null, [Validators.required, Validators.min(10), Validators.max(120)]],

    //  INTERVENTION
    PlanStagHybrid: [null, Validators.required],
    ArchProc: [null, Validators.required],
    ArchDisTech: [null, Validators.required],
    ArchDiscSite: [null, Validators.required],
    ArchDisExt: [null, Validators.required],
    ArchBranReimp: [null, Validators.required],
    ArchBranInnom: [null, Validators.required],
    ArchBranRSub: [null, Validators.required],
    ArchBranRComm: [null, Validators.required],
    ArchBranLComm: [null, Validators.required],
    ArchBranLSub: [null, Validators.required],
    ArchBranLVert: [null, Validators.required],
    ArchBranOth: [null, Validators.required],

    DescAortaProc: [null, Validators.required],
    DescAortaLoc: [null, Validators.required],
    AortaInterReimp: [null, Validators.required],
    AortaDisZone: [null, Validators.required],
    AortaVisceral: [null, Validators.required],
    AortaViscCel: [null, Validators.required],
    AortaViscSup: [null, Validators.required],
    AortaViscRenR: [null, Validators.required],
    AortaViscRenL: [null, Validators.required],

    EndovasProc: [null, Validators.required],
    EndovasAccess: [null, Validators.required],
    EndovasPercAcc: [null, Validators.required],
    EndoProxZone: [null, Validators.required],
    EndoDistalZone: [null, Validators.required],
    EndovasTAVR: [null, Validators.required],
    EndovasTEVAR: [null, Validators.required],

    //  Arch Vessel management
    Innominate: [null, Validators.required],
    InAortaInnom: [null, Validators.required],
    InAortaCarotid: [null, Validators.required],
    InAortaSubclav: [null, Validators.required],
    InCaroSubclav: [null, Validators.required],
    InOther: [null, Validators.required],
    LeftCarotid: [null, Validators.required],
    LTCaroAortaCaro: [null, Validators.required],
    LTCaroInnomCaro: [null, Validators.required],
    LTCaroCarotid: [null, Validators.required],
    LTCaroOther: [null, Validators.required],
    LeftSubclavian: [null, Validators.required],
    LTSubAortaSub: [null, Validators.required],
    LTSubCarotidSub: [null, Validators.required],
    LTSubOther: [null, Validators.required],
    OthArchVes: [null, Validators.required],
    OthInnomCaro: [null, Validators.required],
    OthInnomSub: [null, Validators.required],
    OthSubSub: [null, Validators.required],
    OthOther: [null, Validators.required],

    //  Visceral Vessel management
    Celiac: [null, Validators.required],
    CeliacAortaCeli: [null, Validators.required],
    CeliacIliacCeliac: [null, Validators.required],
    CeliacOther: [null, Validators.required],

    SupMesenteric: [null, Validators.required],
    SupMesAortaSuMe: [null, Validators.required],
    SupMesIliacSupMe: [null, Validators.required],
    SupMesOther: [null, Validators.required],

    RightRenal: [null, Validators.required],
    RtRenAortaRtRe: [null, Validators.required],
    RtRenIliacRtRen: [null, Validators.required],
    RtRenOther: [null, Validators.required],

    LeftRenal: [null, Validators.required],
    LtRenAortaLtRe: [null, Validators.required],
    LtRenIliacLtRen: [null, Validators.required],
    LtRenOther: [null, Validators.required],

    RightIliac: [null, Validators.required],
    RtIliacFemFem: [null, Validators.required],
    RtIliacOther: [null, Validators.required],

    LeftIliac: [null, Validators.required],
    LtIliacFemFem: [null, Validators.required],
    LtIliacOther: [null, Validators.required],

    IntIliacPres: [null, Validators.required],

    OthVisVes: [null, Validators.required],
    OthVisAortOth: [null, Validators.required],
    OthVisIliacOth: [null, Validators.required],
    OthVisOther: [null, Validators.required],

    DisProxTearCov: [null, Validators.required],
    EndoEndProc: [null, Validators.required],
    EndoEndProcTy: [null, Validators.required],

    ConvToOpen: [null, Validators.required],
    ConvToOpenRes: [null, Validators.required],
    IntDisExten: [null, Validators.required],

    UnintRup: [null, Validators.required],
    UnintRupLoc: [null, Validators.required],

    SpinalDrain: [null, Validators.required],
    MotorEvoke: [null, Validators.required],
    MotorEvokeAb: [null, Validators.required],
    SomatEvoke: [null, Validators.required],
    SomatEvokeAb: [null, Validators.required],
    IntraOpEEG: [null, Validators.required],
    IntraOpEEGAb: [null, Validators.required],
    IntraOpIVUS: [null, Validators.required],
    TransDoppler: [null, Validators.required],
    IntraOpAng: [null, Validators.required],
    IntraOpAngVol: [null, [Validators.required, Validators.min(0), Validators.max(2000)]],
    IntraOpAngFlTm: [null, [Validators.required, Validators.min(0), Validators.max(300)]],

    ADevIns: [null, Validators.required],

    ADevLoc01: [null, Validators.required],
    ADevDelMeth01: [null, Validators.required],
    ADevOut01: [null, Validators.required],
    ADevModel01: [null, Validators.required],
    ADevUDI01: [null, Validators.required],

    ADevLoc02: [null, Validators.required],
    ADevDelMeth02: [null, Validators.required],
    ADevOut02: [null, Validators.required],
    ADevModel02: [null, Validators.required],
    ADevUDI02: [null, Validators.required],

    ADevLoc03: [null, Validators.required],
    ADevDelMeth03: [null, Validators.required],
    ADevOut03: [null, Validators.required],
    ADevModel03: [null, Validators.required],
    ADevUDI03: [null, Validators.required],

    ADevLoc04: [null, Validators.required],
    ADevDelMeth04: [null, Validators.required],
    ADevOut04: [null, Validators.required],
    ADevModel04: [null, Validators.required],
    ADevUDI04: [null, Validators.required],

    ADevLoc05: [null, Validators.required],
    ADevDelMeth05: [null, Validators.required],
    ADevOut05: [null, Validators.required],
    ADevModel05: [null, Validators.required],
    ADevUDI05: [null, Validators.required],

    ADevLoc06: [null, Validators.required],
    ADevDelMeth06: [null, Validators.required],
    ADevOut06: [null, Validators.required],
    ADevModel06: [null, Validators.required],
    ADevUDI06: [null, Validators.required],

    ADevLoc07: [null, Validators.required],
    ADevDelMeth07: [null, Validators.required],
    ADevOut07: [null, Validators.required],
    ADevModel07: [null, Validators.required],
    ADevUDI07: [null, Validators.required],

    ADevLoc08: [null, Validators.required],
    ADevDelMeth08: [null, Validators.required],
    ADevOut08: [null, Validators.required],
    ADevModel08: [null, Validators.required],
    ADevUDI08: [null, Validators.required],

    ADevLoc09: [null, Validators.required],
    ADevDelMeth09: [null, Validators.required],
    ADevOut09: [null, Validators.required],
    ADevModel09: [null, Validators.required],
    ADevUDI09: [null, Validators.required],

    ADevLoc10: [null, Validators.required],
    ADevDelMeth10: [null, Validators.required],
    ADevOut10: [null, Validators.required],
    ADevModel10: [null, Validators.required],
    ADevUDI10: [null, Validators.required],

    ADevLoc11: [null, Validators.required],
    ADevDelMeth11: [null, Validators.required],
    ADevOut11: [null, Validators.required],
    ADevModel11: [null, Validators.required],
    ADevUDI11: [null, Validators.required],

    ADevLoc12: [null, Validators.required],
    ADevDelMeth12: [null, Validators.required],
    ADevOut12: [null, Validators.required],
    ADevModel12: [null, Validators.required],
    ADevUDI12: [null, Validators.required],

    ADevLoc13: [null, Validators.required],
    ADevDelMeth13: [null, Validators.required],
    ADevOut13: [null, Validators.required],
    ADevModel13: [null, Validators.required],
    ADevUDI13: [null, Validators.required],

    ADevLoc14: [null, Validators.required],
    ADevDelMeth14: [null, Validators.required],
    ADevOut14: [null, Validators.required],
    ADevModel14: [null, Validators.required],
    ADevUDI14: [null, Validators.required],

    ADevLoc15: [null, Validators.required],
    ADevDelMeth15: [null, Validators.required],
    ADevOut15: [null, Validators.required],
    ADevModel15: [null, Validators.required],
    ADevUDI15: [null, Validators.required],
  },
  sectionM3: {
    OCarCongDiag1: [null, Validators.required],
    OCarCongDiag2: [null, Validators.required],
    OCarCongDiag3: [null, Validators.required],
    OCarCongProc1: [null, Validators.required],
    OCarCongProc2: [null, Validators.required],
    OCarCongProc3: [null, Validators.required],
  },
  sectionN: {
    ONCCarEn: [null, Validators.required],
    ONCOVasc: [null, Validators.required],
    ONCOThor: [null, Validators.required],
    ONCOther: [null, Validators.required],
  },
  sectionO: {
    PostOpPeakGlu: [null, [Validators.required, Validators.min(30), Validators.max(1500)]],
    PostCreat: [null, [Validators.required, Validators.min(0.1), Validators.max(30.0)]],
    PostopHemoglobin: [null, [Validators.required, Validators.min(1.0), Validators.max(50.0)]],
    PostopHct: [null, [Validators.required, Validators.min(1.0), Validators.max(99.99)]],
    BldProd: [null, Validators.required],
    BdRBCU: [null, [Validators.required, Validators.min(0), Validators.max(99)]],
    BdFFPU: [null, [Validators.required, Validators.min(0), Validators.max(99)]],
    BdCryoU: [null, [Validators.required, Validators.min(0), Validators.max(99)]],
    BdPlatU: [null, [Validators.required, Validators.min(0), Validators.max(99)]],
    ExtubOR: [null, Validators.required],
    PostopIntub: [null, Validators.required],
    VentHrsA: [null, [Validators.required, Validators.min(0.1), Validators.max(5000.0)]],
    VentHrsTot: [null, [Validators.required, Validators.min(0.0), Validators.max(6000.0)]],
    ICUVisit: [null, Validators.required],
    ICUInHrs: [null, [Validators.required, Validators.min(0.1), Validators.max(5000.0)]],
    ICUReadm: [null, Validators.required],
    ICUAdHrs: [null, [Validators.required, Validators.min(0.1), Validators.max(5000.0)]],
    POpTTEch: [null, Validators.required],
    POpTTAR: [null, Validators.required],
    POpAortParaLk: [null, Validators.required],
    POpTTMR: [null, Validators.required],
    POpMitParaLk: [null, Validators.required],
    POpTTTR: [null, Validators.required],
    POpTTPu: [null, Validators.required],
    POpEFD: [null, Validators.required],
    POpEF: [null, [Validators.required, Validators.min(1.0), Validators.max(99.0)]],
    POpEnzDrawn: [null, Validators.required],
    POpPkCKMB: [null, [Validators.min(0.0), Validators.max(5000.0)]],
    POpPkTrI: [null, [Validators.min(0.0), Validators.max(5000.0)]],
    POpPkTrT: [null, [Validators.min(0.0), Validators.max(5000.0)]],
    POpEKG: [null, Validators.required],
  },
  sectionP: {
    SurSInf: [null, Validators.required],
    CSternalSupInf: [null, Validators.required],
    DeepSternInf: [null, Validators.required],
    DeepSternInfDt: [null, Validators.required],
    CIThor: [null, Validators.required],
    ConduitHarv: [null, Validators.required],
    CanSite: [null, Validators.required],
    WoundInter: [null, Validators.required],
    WoundIntOpen: [null, Validators.required],
    WoundIntVac: [null, Validators.required],
    WoundIntMuscle: [null, Validators.required],
    WoundIntOmental: [null, Validators.required],

    Complics: [null, Validators.required],
    COpReBld: [null, Validators.required],
    COpReBldTim: [null, Validators.required],
    COpReVlv: [null, Validators.required],
    CReintMI: [null, Validators.required],
    CReintMIVes: [null, Validators.required],
    CReintMIIntTy: [null, Validators.required],
    CAortReint: [null, Validators.required],
    CAortReintTy: [null, Validators.required],
    COpReOth: [null, Validators.required],
    COpReNon: [null, Validators.required],
    COpPlndDelay: [null, Validators.required],
    CSternal: [null, Validators.required],
    CSternalDehis: [null, Validators.required],

    CSepsis: [null, Validators.required],
    CSepsisPBC: [null, Validators.required],

    CNStrokP: [null, Validators.required],
    CNStrokTTIA: [null, Validators.required],
    CNEnceph: [null, Validators.required],
    CNComa: [null, Validators.required],

    CNParal: [null, Validators.required],
    CNParalTy: [null, Validators.required],
    CNParesis: [null, Validators.required],
    CNParesisTy: [null, Validators.required],
    PhrenNrvInj: [null, Validators.required],
    RecLarynNrvInj: [null, Validators.required],

    CPVntLng: [null, Validators.required],
    CPPneum: [null, Validators.required],
    CVTE: [null, Validators.required],
    PulmEmb: [null, Validators.required],
    DVT: [null, Validators.required],
    CPlEff: [null, Validators.required],
    PostOpPneumo: [null, Validators.required],

    CRenFail: [null, Validators.required],
    CRenDial: [null, Validators.required],
    DialDur: [null, Validators.required],
    DialStat: [null, Validators.required],
    CUltraFil: [null, Validators.required],

    CVaIlFem: [null, Validators.required],
    CVaLbIsc: [null, Validators.required],

    CMAD: [null, Validators.required],
    CMADCanIns: [null, Validators.required],
    CMADHem: [null, Validators.required],
    CMADThromEm: [null, Validators.required],
    CMADHemolytic: [null, Validators.required],
    CMADInf: [null, Validators.required],
    CMADOther: [null, Validators.required],

    CRhythmDis: [null, Validators.required],
    COtArrst: [null, Validators.required],
    COtAortEndo: [null, Validators.required],
    COtAortEndoTy: [null, Validators.required],
    COtAortRupt: [null, Validators.required],
    CVaAoDis: [null, Validators.required],
    CVaAoDisTy: [null, Validators.required],
    COtAortSide: [null, Validators.required],
    COtAortTear: [null, Validators.required],
    COtCoag: [null, Validators.required],
    COtTamp: [null, Validators.required],
    COtGI: [null, Validators.required],
    COtLiver: [null, Validators.required],
    COtMSF: [null, Validators.required],
    COtAFib: [null, Validators.required],
    COtOther: [null, Validators.required],
  },
  sectionQ: {
    LFUDate: [null, Validators.required],
    Mt30Stat: [null, Validators.required],
    Mt30StatMeth: [null, Validators.required],
    DischMortStat: [null, Validators.required],
    DischDt: [null, Validators.required],
    DisLoctn: [null, Validators.required],
    CardRef: [null, Validators.required],
    SmokCoun: [null, Validators.required],

    DCASA: [null, Validators.required],
    DCADP: [null, Validators.required],
    DCOthAntiplat: [null, Validators.required],
    DCDirThromIn: [null, Validators.required],
    DCCoum: [null, Validators.required],
    DCFactorXa: [null, Validators.required],
    DCNovOrAnti: [null, Validators.required],
    DCOthAnticoag: [null, Validators.required],
    DCACE: [null, Validators.required],
    DCAmiodarone: [null, Validators.required],
    DCBeta: [null, Validators.required],
    DCLipLowStat: [null, Validators.required],
    DCLipLowNonStat: [null, Validators.required],

    MtDate: [null, Validators.required],
    MtCause: [null, Validators.required],
    InHospDthLoc: [null, Validators.required],
    MtOpD: [null, Validators.required],
    PostDisDthLoc: [null, Validators.required],
  },
  sectionR: {
    Readmit: [null, Validators.required],
    ReadmitDt: [null, Validators.required],
    ReadmRsn: [null, Validators.required],
    ReadmPro: [null, Validators.required],
    ReadmAortIntTy: [null, Validators.required],
    ReadmAortIntInd: [null, Validators.required],
  },
  sectionS: {
    AnesCareTeamMod: [null, Validators.required],
    PainScorePre: [null, Validators.required],
    TransfAlg: [null, Validators.required],
    CellSavVol: [null, [Validators.required, Validators.min(0), Validators.max(10000)]],
    HepUse: [null, Validators.required],
    TotHep: [null, [Validators.required, Validators.min(0), Validators.max(200000)]],
    HepMgmt: [null, Validators.required],
    TotProt: [null, [Validators.required, Validators.min(0), Validators.max(1000)]],
    AntithromDose: [null, [Validators.required, Validators.min(0), Validators.max(7500)]],
    IntraViscoTest: [null, Validators.required],

    VolAgentUsed: [null, Validators.required],
    VolAgentIso: [null, Validators.required],
    VolAgentSevo: [null, Validators.required],
    VolAgentDes: [null, Validators.required],
    VolAgentOth: [null, Validators.required],
    VolAgentTimPre: [null, Validators.required],
    VolAgentTimDur: [null, Validators.required],
    VolAgentTimPost: [null, Validators.required],
    VolAgentTimMaint: [null, Validators.required],

    DexIntra: [null, Validators.required],
    PropIntra: [null, Validators.required],
    MidazIntra: [null, [Validators.required, Validators.min(0), Validators.max(50)]],
    TotInsuIntra: [null, [Validators.required, Validators.min(0), Validators.max(200)]],
    PreAnesthBPSys: [null, [Validators.required, Validators.min(50), Validators.max(300)]],
    PreAnesthBPDia: [null, [Validators.required, Validators.min(20), Validators.max(150)]],
    PreAnesthBPMean: [null, [Validators.required, Validators.min(30), Validators.max(150)]],
    PreAnesthHR: [null, [Validators.required, Validators.min(30), Validators.max(170)]],
    PACIntra: [null, Validators.required],
    CoreTempSrc: [null, Validators.required],
    CoreTempMax: [null, [Validators.required, Validators.min(33.0), Validators.max(41.0)]],
    NitricOxIntraop: [null, Validators.required],
    TotCrystAnesth: [null, [Validators.required, Validators.min(0), Validators.max(10000)]],
    TotColloidAnesth: [null, [Validators.required, Validators.min(0), Validators.max(4000)]],
    TotAlbumAnesth: [null, [Validators.required, Validators.min(0), Validators.max(2000)]],
    GlucTroughIntraop: [null, [Validators.required, Validators.min(20), Validators.max(250)]],
    VasodilIntraop: [null, Validators.required],
    IntraProcEEG: [null, Validators.required],

    IntraOpPreTEE: [null, Validators.required],
    PreLVEFMeas: [null, Validators.required],
    PreLVEF: [null, [Validators.required, Validators.min(1.0), Validators.max(99.0)]],
    PreRVFx: [null, Validators.required],
    PreMR: [null, Validators.required],
    PreMS: [null, Validators.required],
    PreAR: [null, Validators.required],
    PreAS: [null, Validators.required],
    PreAVAAssessed: [null, Validators.required],
    PreAVA: [null, [Validators.required, Validators.min(0.2), Validators.max(5.0)]],
    PreTR: [null, Validators.required],
    PrePFO: [null, Validators.required],
    AscAoAssessed: [null, Validators.required],
    MxAscAo: [null, [Validators.required, Validators.min(1.0), Validators.max(8.0)]],
    MxAscAoThick: [null, [Validators.required, Validators.min(0.0), Validators.max(20.0)]],
    AsAthMo: [null, Validators.required],
    AoArcVis: [null, Validators.required],
    MxArcAth: [null, [Validators.required, Validators.min(0.0), Validators.max(20.0)]],
    ArcAthMo: [null, Validators.required],

    CPBUsed: [null, Validators.required],
    RetrAutolPrim: [null, Validators.required],
    TotCrystPerf: [null, [Validators.required, Validators.min(0), Validators.max(10000)]],
    TotColloidPerf: [null, [Validators.required, Validators.min(0), Validators.max(4000)]],
    TotAlbumPerf: [null, [Validators.required, Validators.min(0), Validators.max(2000)]],
    HemofilPerf: [null, [Validators.required, Validators.min(0), Validators.max(10000)]],
    InotropWeanCPB: [null, Validators.required],
    VasopWeanCPB: [null, Validators.required],

    IntraOpPostTEE: [null, Validators.required],
    PostSAM: [null, Validators.required],
    RetCPBEch: [null, Validators.required],
    PostLVEFMeas: [null, Validators.required],
    PostLVEF: [null, [Validators.required, Validators.min(1.0), Validators.max(99.0)]],
    PostRVFx: [null, Validators.required],

    IntraCardArr: [null, Validators.required],

    ORDeath: [null, Validators.required],
    PostTempMeas: [null, Validators.required],
    PostCoreTemp: [null, [Validators.required, Validators.min(30.0), Validators.max(41.0)]],
    PostINRMeas: [null, Validators.required],
    PostINR: [null, [Validators.required, Validators.min(0.5), Validators.max(5.0)]],
    PostWBCMeas: [null, Validators.required],
    PostWBC: [null, [Validators.required, Validators.min(1000), Validators.max(50000)]],
    PostPltMeas: [null, Validators.required],
    PostPlt: [null, [Validators.required, Validators.min(5000), Validators.max(500000)]],
    PostHCTMeas: [null, Validators.required],
    PostHCT: [null, [Validators.required, Validators.min(10.0), Validators.max(60.0)]],
    PostFibrinMeas: [null, Validators.required],
    PostFibrin: [null, [Validators.required, Validators.min(0.0), Validators.max(1200.0)]],
    PostLactMeas: [null, Validators.required],
    PostLact: [null, [Validators.required, Validators.min(0), Validators.max(20)]],
    DexPost: [null, Validators.required],
    PropPost: [null, Validators.required],
    PostopDel: [null, Validators.required],
    PostHITAnti: [null, Validators.required],
    PainScorePOD3: [null, Validators.required],
    PainScoreDisch: [null, Validators.required],
  },
};
